### ISSUE TITLE
Ignore files when copying to template

### ISSUE THREAD

**Issue by phm07** [CloudNetService/CloudNet-v3#1018]
### Describe the new feature

When copying dynamic server instances into the template folder, often times a lot of unnecessary files get copied over, like logs or temporary files. It would be nice if the program checked for a `.copyignore` file and excluded the listed files from copying, similar to a `.gitignore` file. 

### Why do you need this feature?

This would decrease the clutter in template folders and reduce file size.

### Alternatives

-

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
You can specify which files to include or exclude when copying. I don't see why we would need to have an extra file for that

**Comment by phm07** [comment]
> You can specify which files to include or exclude when copying. I don't see why we would need to have an extra file for that

So that you don't have to specify all files each time you want to use the command.

**Comment by 0utplay** [comment]
Still not convinced about this
