### ISSUE TITLE
Only send the player to one service of a task / group when using PlayerExecutor#connectToGroup/Task

### ISSUE THREAD

**Issue by 0utplay** [CloudNetService/CloudNet-v3#1025]
### Describe the new feature

The connectToGroup and connectToTask methods of the PlayerExecutor connect the desired player to ALL services of the group / task instead of just connecting to one. Change this behavior to send the player to one service.

### Why do you need this feature?

The player sends a connection request to each service instead of one and might get on a service that does not match the ServerSelectorType

### Alternatives

The api user would have to filter the services on himself and these methods would be useless.

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by derklaro** [comment]
We should also consider retries... If an api user calls f. ex. `connectToGroup` there is neither an indication if the connect was successful nor a way to enable retries (try the next service if the first one denies the connection).
