### ISSUE TITLE
Permissions not working on high players

### ISSUE THREAD

**Issue by Tynopia** [CloudNetService/CloudNet-v3#1052]
### Stacktrace

```
No error on console.
```

We have been observing for several weeks now that the permissions are not functioning when there are approximately 300 players (+/- 20). These 300 players are not spread across multiple servers but are on one specific subserver (Citybuild). If we just restarted and there are 300 players, it still works. But if we wait a bit, it stops working again. However, if we wait until there are about 250 players, it works again. We are wondering if it is CloudNet or Paper 1.19.2 that is causing this problem...

### Actions to reproduce

- One Minute After Restart (300 Players) (14:38)
![Screenshot 2023-01-03 144046](https://user-images.githubusercontent.com/65678882/210369963-00096c90-5511-48a8-bb3d-a4905ab9bb6b.png)
- 10 Minutes After Restart (300 Players). (14:48 Permissions not working)
![image](https://user-images.githubusercontent.com/65678882/210371703-972d5310-3663-4354-9b3a-92073b7181fb.png)

These are my permissions. But it's not just me who can't do anything - normal players can't go to plots, for example.

![image](https://user-images.githubusercontent.com/65678882/210372061-7eff7f17-41a7-40a9-8389-eb0e8f8606b1.png)

### CloudNet version

[03.01 14:47:52.004] INFO: CloudNet Blizzard 4.0.0-RC5 4ec2a84d
[03.01 14:47:52.004] INFO: Discord: <https://discord.cloudnetservice.eu/>
[03.01 14:47:52.004] INFO: 
[03.01 14:47:52.004] INFO: ClusterId: ***
[03.01 14:47:52.004] INFO: NodeId: Node-1-Testserver
[03.01 14:47:52.004] INFO: Head-NodeId: Node-2-Testserver
[03.01 14:47:52.004] INFO: CPU usage: (P/S) 1.91/4.49/100%
[03.01 14:47:52.004] INFO: Node services memory allocation (U/R/M): 11264/19456/16000 MB
[03.01 14:47:52.004] INFO: Threads: 75
[03.01 14:47:52.004] INFO: Heap usage: 54/256MB
[03.01 14:47:52.004] INFO: JVM: Private Build 17 (OpenJDK 64-Bit Server VM 17.0.5+8-Ubuntu-2ubuntu120.04)
[03.01 14:47:52.005] INFO: Update Repo: CloudNetService/launchermeta, Update Branch: beta

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by Tynopia** [comment]
**As soon as there are fewer than exactly 300 players, it works again.**
![image](https://user-images.githubusercontent.com/65678882/210376043-d7c863f9-52dd-413c-945d-04b07e4b9b5b.png)
![image](https://user-images.githubusercontent.com/65678882/210376514-e1bc9a7f-b30b-4910-bfda-aca47aca313c.png)

**Exactly at 300 players.**
![image](https://user-images.githubusercontent.com/65678882/210376359-840b0daa-c396-4619-9d1d-ef254d483967.png)
![image](https://user-images.githubusercontent.com/65678882/210376403-5f8eea16-3b2c-4060-b08e-faaee49bf9ce.png)

**Comment by derklaro** [comment]
Are permissions on the proxy still working?

**Comment by Tynopia** [comment]
![image](https://user-images.githubusercontent.com/65678882/210387427-1eb7dd29-2a3d-4560-b7be-417035fca3c9.png)
Yes, "tps" and other stuff are not working. But /server still working

**Comment by Tynopia** [comment]
We just set the user limit to 299 and it still occurs after a while.

**Comment by derklaro** [comment]
I need to take a deeper look then, cause the same code that runs on the proxies is used on the servers to calculate the permissions...

**Comment by Tynopia** [comment]
![image](https://user-images.githubusercontent.com/65678882/211152929-3fdd3eee-1047-4e8e-a78d-ca619e3b381e.png)
We have also tried what happens if I have OP. Before, it did not work (with * and all other permissions) but with OP it works immediately.

**Comment by Tynopia** [comment]
We increased the slots from 300 to 800 to prevent the server from filling up. The permissions worked again immediately. We let the server run at full capacity with 500 slots and captured the slots back to 300. The permissions stopped working again immediately....

**Comment by derklaro** [comment]
Are you doing server reloads (or something similar)?

**Comment by Tynopia** [comment]
Every day at 04:30, the entire network (each subserver) is restarted. Nothing is typically restarted or reloaded during the day.
