### ISSUE TITLE
Adding nodes in the cluster

### ISSUE THREAD

**Issue by Eptiiix** [CloudNetService/CloudNet-v3#1114]
### Describe the new feature

automatically add nodes to other nodes if added on head node.

as example:
u got a new node, u install cloudnet, provide the cluster id etc.
then u go to the head node, run "clu add Node-X xxx.xxx.xxx.xxx:1410" and the new node gets automatically added to the existing nodes in the cluster.

### Why do you need this feature?

its really hard to add a new node to the cluster as we need to connect to every single node and run "clu add Node-X xxx.xxx.xxx.xxx:1410"

### Alternatives

i guess there is no alternative because the node does not know the addresses of the other nodes

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
As far as I can tell this is already present 
https://github.com/CloudNetService/CloudNet-v3/blob/nightly/node/src/main/java/eu/cloudnetservice/node/provider/NodeClusterNodeProvider.java#L87-L103
