### ISSUE TITLE
proxy cloud perms

### ISSUE THREAD

**Issue by gamingcodedev** [CloudNetService/CloudNet-v3#1145]
### Stacktrace

in proxy the cloud perms inherits of groups does not work

### Actions to reproduce

.

### CloudNet version

3.4.5

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0xIO32** [comment]
CloudPerms will be removed in rc9 btw

**Comment by 0utplay** [comment]
Inheritance is working - not enough information to reproduce
