### ISSUE TITLE
Set tablist on join everytime also if there is no animation

### ISSUE THREAD

**Issue by Smoofy19** [CloudNetService/CloudNet-v3#1170]
### Describe the new feature

The tablist header and footer should also be set on player join if the animation is removed.

### Why do you need this feature?

I need this that I can change the header and footer via plugin and that the default header and footer is not always set

### Alternatives

-

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
I don't really understand the problem here. Why should header & footer be set, although they are deactivated in the config and why should that be necessary to write a separate plugin for it?

**Comment by Smoofy19** [comment]
> I don't really understand the problem here. Why should header & footer be set, although they are deactivated in the config and why should that be necessary to write a separate plugin for it?

It shouldn't be deactivated if there is no animation. The problem is, if I want to change the tablist via another plugin (e.g. when a player enters a region), then it resets after the animation time and I don't want that

**Comment by 0utplay** [comment]
Why don't you just deactivate the tablist if you are replacing it?

**Comment by Smoofy19** [comment]
> Why don't you just deactivate the tablist if you are replacing it?

Because I want to replace the tablist on the Lobby only.

**Comment by 0utplay** [comment]
I dont feel like that is a case we should address for. This is just sketchy as this only works if there is no updates in the header / footer and that means that we can't provide full functionality of the module while supporting what you are asking for
