### ISSUE TITLE
ProtocolLib could not be downloaded

### ISSUE THREAD

**Issue by Omuboid-Development** [CloudNetService/CloudNet-v3#1211]
### Stacktrace

```
![image](https://user-images.githubusercontent.com/122204187/233859540-062c634b-71ef-4926-b60f-0525602f4e87.png)
```

### Actions to reproduce

I only set up a new cloudnet server on a server by prepaidhost

### CloudNet version

CloudNet Earthquake 3.4.5-RELEASE-0f8f0d7

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
Because ProtocolLib has changed from maven to gradle, the URL on the Jenkins has also changed. The latest snapshot has already received an update, for the release I advise you to download ProtocolLib yourself and put it into the global/server template.
