### ISSUE TITLE
Hex colors and other chat component features are lost when sending them via CloudNet

### ISSUE THREAD

**Issue by itsTyrion** [CloudNetService/CloudNet-v3#1216]
### Actions to reproduce

send a chat message or title in Component form to a player via CloudNet player executor on Bukkit/Paper or Bungeecord/Waterfall or broadcast it. 

Most chat component features, including hex colors, are lost

### CloudNet version

CloudNet Blizzard 4.0.0-RC8 61a0ada8
Discord: <https://discord.cloudnetservice.eu/>

ClusterId: 3eee53da-****-4de9-****-a04504515c93
NodeId: master
Head-NodeId: master
CPU usage: (P/S) 3.42/8.85/100%
Node services memory allocation (U/R/M): 5376/5376/15000 MB
Threads: 55
Heap usage: 169/384MB
JVM: Debian 17 (OpenJDK 64-Bit Server VM 17.0.6+10-Debian-1deb11u1)
Update Repo: CloudNetService/launchermeta, Update Branch: beta

### Other

I noticed the use of Adventure LegacyComponentSerializer.
Is there a reason that `BungeeComponentSerializer` wasn't used? (or `GsonComponentSerializer`, which is already a dep, and `net.md_5.bungee.chat.ComponentSerializer.parse()`)

I could open a PR, but I'm not sure how to proceed regarding 2 things: 
- the versioning system, because adventure-text-serializer-bungeecord uses a different version than adventure-text-serializer-gson or -legacy for some reason. Just add them to libs.versions.toml? Or don't and use the Gson serializer + bungee-chat parser?
- versions that don't support hex colors. Checking the protocol version in methods like sendMessage? (20w17a and above (1.16))

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
If the versioning is different you can just create a second version ref for that dependency. Regarding the second issue we might want to guess the closest color to the given hex color in versions that do not support hex at all (Adventure should provide this)

**Comment by itsTyrion** [comment]
... I just realized I forgot to push and PR after implementing it. whoops.
