### ISSUE TITLE
Allowing CORS-Requests

### ISSUE THREAD

**Issue by thxrben** [CloudNetService/CloudNet-v3#1224]
### Describe the new feature

I cannot use the REST-API Module due to CORS. 
Browsers and the applications below (js) do not allow any non-cors request to include a Authorization: Bearer header.

Therefore, I need the "Access-Control-Allow-Origin" Header set to * on all endpoints.

### Why do you need this feature?

I cannot interface with the REST-API properly in browser-environments due to CORS. Therefore, any JS that makes requests to the CloudNet-REST-API Module cannot authenticate.

### Alternatives

If not possible to add due to restrictions (e.g. cluster communication etc.), it would be sufficent to have a Proxy that at least responds with the "Access-Control-Allow-Origin" header set to *, so that the cluster could just continue using the "unsafe" API and all "Public-API calls" could occur on a different port.

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
Are you shure that CORS is not set? I think that most browsers do not allow the wildcard '*' when using auth.

![image](https://github.com/CloudNetService/CloudNet-v3/assets/60936899/ee2fe5d1-b022-4bc3-9899-21acb92974da)

**Comment by thxrben** [comment]
The original code i used to fetch it:

```
export async function getClusterInfo() {

    const response = await fetch("/api/v2/cluster", {
        method: "GET",
        mode: "cors",
        headers: new Headers({
            'Authorization': "Bearer "+token
        })
    });

    const result = await response.json();
    return (result?.success === true ? result : "N/A");
}
```

This resulted in the typical preflight which the Server just responds with 401 if I recall correctly.

Its currently planned to create a web-application that provides a UI for the CloudNet-Suite. In the end, the web-application is not meant to run in a browser, but packaged (most likely) in a Electron app.

In the end, since its a web-app, regardless of how its deployed, it will be displayed using a request to a internal IP (such as 127.0.0.1:3000). Because of this, I cannot just make "non-cors" requests (which remove the Auth-Header) to the server, and said "Access-Control-Allow-Origin" header is not provided by the server, so I also cannot use "cors".

I got around this limitation for developing by using the react-proxy, but this wont be suitable for a later deployment. 


Also, using a REST-Client (Boomerang - Web Extension) the API can be called with no issues. But running JS-Code that is served on some kind of website is impossible.
I also speculated of adding a client-side proxy which just adds said header when receiving the response, but that only adds overhead.


In regards to your question: I think that I mistook the OPTIONS-Request with the actual POST-Request. On the Options-Answer (which is I think 401 when mode: "cors" via fetch-api, I can check tomorrow) said header is not set, or the HTTP-Server does not answer correctly or does not answer at all to OPTIONS-Requests.

EDIT: Fixed formatting

**Comment by MarkusTieger** [comment]
I already mentioned that bug: https://discord.com/channels/325362837184577536/818777626663321671/1085989736096735393

The Header is present on a normal request. But the "OPTIONS" and not the "GET" request will be used by the browser to see if the header is present which follows in a 404 error without the header.
![image](https://github.com/CloudNetService/CloudNet-v3/assets/77546847/87dad5a9-6b9f-44c3-a7f8-9f374861cd51)

**Comment by thxrben** [comment]
The fix linked (#1264) is functional, I will close this as "resolved".
I assume the fix will get implemented in the RC10.

**Comment by docimin** [comment]
> The fix linked (#1264) is functional, I will close this as "resolved". I assume the fix will get implemented in the RC10.

I don't think it will, AFAIK they said in Discord that they want to make a cleaner way of the CORS settings implementation, hence why it's blocked

**Comment by thxrben** [comment]
Sigh, IMO this is already pretty clean. Its not even that big of a PR.
If they dont, I will have to manually fix every version with these commits so I can work properly.
But lets see, maybe there is a better solution.

**Comment by 0xIO32** [comment]
> Sigh, IMO this is already pretty clean. Its not even that big of a PR. If they dont, I will have to manually fix every version with these commits so I can work properly. But lets see, maybe there is a better solution.

A reverse proxy would be much less work than updating every version of it and compiling it

**Comment by docimin** [comment]
There's an upcoming version most likely in RC-10 with new and updated Endpoints, as well as CORS I think.
