### ISSUE TITLE
Custom type for runner

### ISSUE THREAD

**Issue by DormantCat** [CloudNetService/CloudNet-v3#1266]
### Describe the new feature

We have a limited list of startup "cores" BUNGEECORD, VELOCITY, and a couple of other public ones, I suggest adding the ability to launch custom modules, this will increase functionality. Launching, for example, a Discord bot (written in java), Core system or something else

It is much more convenient to run 1 process through which everything is already managed

### Why do you need this feature?

To start, manage processes, to remove restrictions in pre-installed versions!

### Alternatives

Running processes in parallel with Cloud Net - but it's not convenient

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
This is already possible. You can add your own `ServiceEnvironmentType` and same goes for the `ServiceEnvironment `
