### ISSUE TITLE
Add MariaDB Connector/J as an alternative to MySQL Connector/J

### ISSUE THREAD

**Issue by FatildaIV** [CloudNetService/CloudNet-v3#1279]
### Describe the new feature

Add alternative database_provider "mariadb" with MariaDB Connector/J module.

### Why do you need this feature?

MySQL Connector/J 8.0.33 is not compatible with MariaDB 11.0.2 (or newer), as shown in [issue 1277](https://github.com/CloudNetService/CloudNet-v3/issues/1277).

### Alternatives

There are no other alternatives adding support for newer versions of MariaDB while preserving compatibility with legacy MySQL database servers.

### Other

Tested with current code with no issues (all build tests passed successfully, module seems to be working just fine): https://github.com/FatildaIV/CloudNet-v3/commit/2f389807b7c53ee937db22da13f5eec898b0ab6e
[Built module](https://github.com/FatildaIV/CloudNet-v3/releases/tag/modules)

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
Mariadb 11.1.1-rc worked fine for me. What issues are you facing?

**Comment by FatildaIV** [comment]
> Mariadb 11.1.1-rc worked fine for me. What issues are you facing?

MariaDB 11.1.1-RC isn't in production channels, therefore cannot be used in production environment with other (non-CloudNet) services depending on it.
Issue with incompatible MySQL Connector/J is described in [issue 1277](https://github.com/CloudNetService/CloudNet-v3/issues/1277), as mentioned in "Why do you need this feature?" section of this issue.
