### ISSUE TITLE
Online player list via API

### ISSUE THREAD

**Issue by docimin** [CloudNetService/CloudNet-v3#1282]
### Describe the new feature

Being able to read the player list.

Currently you are only able to get the onlineCount via GET /player/onlineCount & registeredCount via GET /player/registeredCount.
However, there is no clean way to get the online player list.

As slightly discussed in the Discord, the route would be useful on GET /player

### Why do you need this feature?

To show a player list in my upcoming public webinterface with the ability to see who exactly is online, and not just the amount of players.

### Alternatives

Listing all known services and reading the players out from that, but this is extremely bad if you have a lot of services.

### Other

Discussed slightly in discord: https://canary.discord.com/channels/325362837184577536/818777626663321671/1136233623469707325

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
This was delivered in RC11 with the reworked rest api
