### ISSUE TITLE
minecraft proxy software gate

### ISSUE THREAD

**Issue by DrFreezyYT** [CloudNetService/CloudNet-v3#1289]
### Describe the new feature

This is a lightweight alternative to Velocity/Bungeecord developed in Go.

### Why do you need this feature?

It's a simple and efficient minecraft proxy

### Alternatives

Velocity, Waterfall, Bungeecord

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by derklaro** [comment]
You need to implement the protocol first, if that is done we can think about wrapping it. That however would be a thing for a different external project (repository) and someone with more Go experience.

**Comment by DrFreezyYT** [comment]
What about including it as a extra in Dockericed Services?

**Comment by 0utplay** [comment]
That won't help with implementing the protocol in Go
