### ISSUE TITLE
Smart doesn't work anymore after you do: reload all

### ISSUE THREAD

**Issue by holoplatte** [CloudNetService/CloudNet-v3#130]
Everytime I use the command reload all the smart module doesnt work anymore.

**Comment by realPanamo** [comment]
What exactly doesn't work anymore?

**Comment by holoplatte** [comment]
When I do a reload all in the console the entire module doesn't work anymore. It isn't shown in the help menu too.

**Comment by holoplatte** [comment]
I mean with that that the servers doesn't get started/stopped automaticly anymore. You also can't use smart reload anymore.
