### ISSUE TITLE
NPCs: Hex Codes

### ISSUE THREAD

**Issue by Roomiiaan** [CloudNetService/CloudNet-v3#1311]
### Describe the new feature

Add an option to also work with hex codes in the CloudNet-NPC module.

### Why do you need this feature?

The CloudNet-Bridge module also allows to work with hex codes. Only a few people still use Minecraft's standard color codes.

### Alternatives

-

### Other

You could also think about supporting the "MiniMessage" format. Paper also has integrated the Adventure API.

https://docs.advntr.dev/minimessage/index.html

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
As far as I can tell you are talking about the info lines right? If thats the case you acutally can use hex color codes but you have to use the bungeecord format (it's horrible) `&x&a&b&c&d&e&f`

**Comment by Roomiiaan** [comment]
> As far as I can tell you are talking about the info lines right? If thats the case you acutally can use hex color codes but you have to use the bungeecord format (it's horrible) `&x&a&b&c&d&e&f`

Best time to support normal hex codes (same as in the bridge module) or adventure api
