### ISSUE TITLE
Service stop doesn't save the world

### ISSUE THREAD

**Issue by holoplatte** [CloudNetService/CloudNet-v3#132]
When you do e.g. service cb01-1 stop the world doesn't get saved. But when you stop the entire cloud the world gets saved.

**Comment by realPanamo** [comment]
Is cb01 a static task?

**Comment by holoplatte** [comment]
Jes, sorry for the late response. cb01 is a static service when I stop it through the /stop command it works but when I use service cb01(-1) stop only some data gets saved.

**Comment by holoplatte** [comment]
It is also so if you stop the entire cloud

**Comment by realPanamo** [comment]
Well, the cloud kills the service after a certain time when stopping, so this might be the issue. Try /save-all before stopping.
