### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by euj3ne** [CloudNetService/CloudNet-v3#1328]
### Stacktrace

https://pastebin.com/q3hrw5kV

### Actions to reproduce

I go to the directory and run sh start.sh or ./start.sh

### CloudNet version

https://github.com/CloudNetService/CloudNet-v3/releases/tag/4.0.0-RC9

### Issue uniqueness

- [ ] Yes, this issue is unique. There are no similar issues.

**Comment by thxrben** [comment]
This looks like your sever does not have a connection to the internet or the request was blocked by your router.

Can you confirm that "ping google.com" works?

**Comment by euj3ne** [comment]
![image](https://github.com/CloudNetService/CloudNet-v3/assets/109100606/098abb5e-da98-43e2-bd0f-d730f863a96a)

**Comment by thxrben** [comment]
That looks good!
You'll most likely have to wait for one of the team members to respond.
I personally didnt have to deal with this issue, so they might have some answers...

**Comment by euj3ne** [comment]
Well, thanks!

**Comment by 0utplay** [comment]
Hey!

Can you please try to download the following file (e.g. using curl)

`https://github.com/CloudNetService/launchermeta/raw/beta/checksums.properties`

**Comment by euj3ne** [comment]
![image](https://github.com/CloudNetService/CloudNet-v3/assets/109100606/582f7584-ca8b-4471-a2ce-c33d3b5e663a)

**Comment by euj3ne** [comment]
I made a firewall by default, installed other dns servers, everything is the same

**Comment by euj3ne** [comment]
![image](https://github.com/CloudNetService/CloudNet-v3/assets/109100606/f669de86-1fee-41a6-990d-8a253177d2c9)

**Comment by 0utplay** [comment]
Can you test `https://raw.githubusercontent.com/CloudNetService/launchermeta/beta/checksums.properties` please

**Comment by euj3ne** [comment]
So where should I put it?
I checked it out, tried to download it. Or was it necessary not to download? And to bring it somewhere?

**Comment by 0utplay** [comment]
I just need to know if it works

**Comment by euj3ne** [comment]
Not

**Comment by 0xIO32** [comment]
Can i see the output of "traceroute github.com" and "nslookup github.com" ?
Or could it be that you only have an ipv6 address and no ipv4?

**Comment by itsTyrion** [comment]
Does your server not have IPv4 connectivity?
If you don't know, do `ping -6 google.com` and `ping -4 google.com`. 

If you don't have IPv4 connectivity, you need to use a public NAT64 service because GitHub, FOR SOME REASON, has no IPv6 support for most parts of the site in 2023
