### ISSUE TITLE
Tablist placeholder for the amount of online players doesn't work

### ISSUE THREAD

**Issue by sobibef119** [CloudNetService/CloudNet-v3#1341]
### Stacktrace

```
Paste your paste link or the raw stack trace here. DO NOT REMOVE THE BACKTICKS!
```

### Actions to reproduce

With waterfall 1.20.4, the amount of online players stays at 0 and doesn't change in the tablist

### CloudNet version

4.0.0-RC9

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
Please provide your configuration, what client version are you using?
