### ISSUE TITLE
MiniMessages in SyncProxy

### ISSUE THREAD

**Issue by DinoMarlir** [CloudNetService/CloudNet-v3#1384]
### Describe the new feature

It would be very nice if you can use MiniMessages in SyncProxy

### Why do you need this feature?

Because MiniMessages (Adventure) are much better than the legacy '`§`-colors`

### Alternatives

You can just keep using '`§`-colors'.

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
Duplicate of #1343
