### ISSUE TITLE
Cloudnet V4 REST API does not provide OPTION method for CORS Preflight

### ISSUE THREAD

**Issue by Phyrone** [CloudNetService/CloudNet-v3#1504]
### Actions to reproduce

1. Use a rest client for the Browser which runs on a different origin
2. (ensure CORS header is properly set in config.json)
3. Try to Access Coudnet Rest API via a cross-origin call
 a. Used Fetch API, but this will apply to all browser APIs
4. After preflight, browser will block call regardless of configured cors header

### CloudNet version

CloudNet Blizzard 4.0.0-RC10 887ad7cf
Discord: <https://discord.cloudnetservice.eu/>

ClusterId: a4710e8e-****-4313-****-2d40cfbcdfab
NodeId: Node-1
Head-NodeId: Node-1
CPU usage: (P/S) .29/42.76/100%
Node services memory allocation (U/R/M): 768/768/24064 MB
Threads: 43
Heap usage: 58/256MB
JVM: Azul Systems, Inc. 21 (OpenJDK 64-Bit Server VM 21.0.4+7-LTS)
Update Repo: CloudNetService/launchermeta, Update Branch: beta

### Other

The Problem:
Before doing cross-origin calls, browsers do a [preflight](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) request using the OPTIONS method.
The Cloudnet API does appear not handle OPTION requests and responds with a 404 not found.
Cloudnet does not include its CORS headers in the Response, and therefor the browser assumes no cross-origin allowed. 

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by derklaro** [comment]
Should work properly now with the new rest module in rc11, if not please open a report in the rest module repository.
