### ISSUE TITLE
Bad classes in gomint

### ISSUE THREAD

**Issue by CraftCoderr** [CloudNetService/CloudNet-v3#185]
**Describe the bug**<br>

Can't build cloudnet modules because of newer java version clasess in gomint.

**Steps for reproducing**<br>

./gradlew cloudnet-modules:cloudnet-bridge:build

**Message**<br>

```
> Task :cloudnet-modules:cloudnet-bridge:compileJava FAILED
D:\Work\CloudNet\cloudnet-modules\cloudnet-bridge\src\main\java\de\dytanic\cloudnet\ext\bridge\gomint\event\GoMintBridgeEvent.java:3: error: cannot access Event
import io.gomint.event.Event;
                      ^
  bad class file: D:\Work\CloudNet\cloudnet-modules\libs\gomint-1.0-SNAPSHOT.jar(io/gomint/event/Event.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
FAILURE: Build failed with an exception.
```

**Please provide us information about your environment and used assets**

OS: Windows 7
Version: Last master commit

**Comment by McRuben** [comment]
You have to build it using Java 11

**Comment by CraftCoderr** [comment]
I think that gradle manages which version to use to build. Should I change sourceCompatibility to 1.11?

**Comment by McRuben** [comment]
No, you don't have to change anything in CloudNet itself. It's only your jdk version

**Comment by realPanamo** [comment]
Yes, you have to build with Java 11.
We can't do much about this, gomint seems to be closed, but we dont want to remove the whole support for it yet

**Comment by CraftCoderr** [comment]
Is it correct, that if something can't be built using Java 8, but can with Java 11, then it must be have sourceCompatibility 1.11?

**Comment by realPanamo** [comment]
Not really, we only use java 8 features, so the source compatibility should be 8 too.
