### ISSUE TITLE
Use a better branch name

### ISSUE THREAD

**Issue by manuelkollus** [CloudNetService/CloudNet-v3#209]
Hello dear competent CloudNet developers,
I would ask you to do a better naming of the branches....

Bad Practice:
http://prntscr.com/qjfsm5

Good Practice:
http://prntscr.com/qjfswi

Here you can learn more about branching workflows for git!
https://medium.com/@patrickporto/4-branching-workflows-for-git-30d0aaee7bf

**Comment by realPanamo** [comment]
👍

**Comment by manuelkollus** [comment]
Okay God!
