### ISSUE TITLE
Can't download dependencies throw 501

### ISSUE THREAD

**Issue by TNG-China** [CloudNetService/CloudNet-v3#213]
![image](https://user-images.githubusercontent.com/21065884/72493596-8ce22900-385c-11ea-85ff-e9eaa74d6fb3.png)

When I run start.bat throw above errors

**Comment by derrop** [comment]
We'll fix this soon, but for now you can go into the directory `launcher/versions/3.2.1-RELEASE` and change every `http://central.maven.org` into `https://repo1.maven.org`.

**Comment by TNG-China** [comment]
As you say to change it, but the problem still exists:
![image](https://user-images.githubusercontent.com/21065884/72500876-6d54fb80-3870-11ea-9831-acd247d245b4.png)

**Comment by TNG-China** [comment]
Uh I see, my fault, It's https not http
