### ISSUE TITLE
Cluster Shutdown doesnt work properly

### ISSUE THREAD

**Issue by AixMC** [CloudNetService/CloudNet-v3#223]
**Describe the bug**<br>
The nodes seems to shutdown nearly completely but the screens keeps open

**Please provide us information about your environment and used assets**
 - OS: Debian 10 on 4 Servers 
 - Version: CloudNet Eruption 3.2.2-RELEASE-6577bbd

**Comment by realPanamo** [comment]
On windows, the cmd window stays open too, but if I click on it and try to type something, it closes instantly.
I don't think that's something we can really fix, the ``stop`` command is being executed on all nodes, so there should be no difference between "normal" stopping and stopping over the cluster.
