### ISSUE TITLE
Ports Freigabe

### ISSUE THREAD

**Issue by Foen100** [CloudNetService/CloudNet-v3#225]
Servus,
wollte mal Fragen welche Ports man alle Freigeben muss. Oder müsste man alle Freigeben?
Vielen Dank für die Antwort :)

**Comment by derrop** [comment]
Hey, von außen muss nur der Proxy frei sein. Die Server müssen natürlich für die Proxies erreichbar sein, aber sollten es nicht für jeden Spieler und die Nodes (falls Cluster genutzt wird) auch nur untereinander.

**Comment by Foen100** [comment]
Vielen Dank, heißt ich muss nur ne MC-Bungeecord Port freigeben?
Und ich habe noch ein Problem mit der Cloud. Jedes mal wenn ich einen Task (Server) wieder starten will (mit "create by NAME 1") kommt: Starting to create the services..., The services couldn't be created und "service NAME-1 start" geht dadurch logischerweise auch nicht. 
Hoffe sie können mir weiterhelfen.

**Comment by derrop** [comment]
Wie viel RAM ist denn noch frei (sieht man mit dem "me" Command) und wie viel benötigt der Task? Sind Wartungen bei dem Task aktiviert?

**Comment by Foen100** [comment]
Habe nicht verändert. Ist neu Installiert. Die RAM anzeige finde ich nirgendswo. Könnte es dies sein? Node services memory allocation: 128/128/5863MB oder Heap usage: 42/456MB

**Comment by derrop** [comment]
Ja, genau das. Dann bräuchte ich einmal bitte den Link aus dem Command "paste all"

**Comment by Foen100** [comment]
https://hasteb.in/vuwoxufo

**Comment by Foen100** [comment]
gerade ging Proxy1 plötzlich wieder. Aber "Proxy" immer noch nicht.

**Comment by derrop** [comment]
Das liegt denke ich daran, dass bei "associatedNodes" nur "Node-1" eingetragen ist, diese existiert aber nicht. Da existiert nur "Node-d1e1d47f".

**Comment by Foen100** [comment]
Sorry, aber noch mal zur Port-Freigabe. Ich erreiche meinen Bungeecord-Server (mit dem Port 25565, welcher auch freigeben ist) nicht. Kann es sein das ich weiter von CloudNet selber freigeben muss?
Vielen Dank

**Comment by derrop** [comment]
Nein, nur der Proxy muss von außen erreichbar sein, sonst nichts.

**Comment by Foen100** [comment]
Merkwürdig das ich ihn nur local erreiche

**Comment by derklaro** [comment]
Schau doch mal in deine Windows Firewall / IpTables Configuration...
