### ISSUE TITLE
Fallbacks not working properly

### ISSUE THREAD

**Issue by derrop** [CloudNetService/CloudNet-v3#233]
**Describe the bug**<br>
When a lobby is starting, users may also be connected to that server, even if it's not running. This causes that the user disconnects with "could not connect to a default or fallback server ..." or it just stays in the loading screen, depending on the state of the server.

**Expected behavior**<br>
The users should be sent to running lobbies and starting lobbies should be ignored.

**Comment by AixMC** [comment]
Maybe add additionally that if there are no running Lobbys, the user will be kicked by the Proxy with a custom message like "No Lobbies online, please try again later" or smth.
