### ISSUE TITLE
Can't runing cloudnet and throw an error

### ISSUE THREAD

**Issue by TNG-China** [CloudNetService/CloudNet-v3#239]
When I first run start.bat, and choose to recommend got this error:
![image](https://user-images.githubusercontent.com/21065884/76001753-8ad54600-5f40-11ea-8488-761ad4fc81d6.png)

**Comment by realPanamo** [comment]
Do you have a recent installation of Java 64 bit on your PC?

**Comment by TNG-China** [comment]
> Do you have a recent installation of Java 64 bit on your PC?

Nope, but I check my java version found I have java7 and java8 both in my PC, 
Sorry, should I use java8 64bit or other 32bit?

**Comment by derklaro** [comment]
As mentioned in the readme the minimum Java version is 8. If you are Not running a 1.8 network it's recomended to use a more recent version like 11.

**Comment by realPanamo** [comment]
Yes, I would recommend to use AdoptOpenJDK 11 64bit for your PC.
https://adoptopenjdk.net
If you want to run 1.8 servers (which isn't recommended), use Java 8 64bit.

**Comment by derklaro** [comment]
**Small collection:**
 - https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot (AdoptOpenJDK 11)
 - https://www.oracle.com/java/technologies/javase-jdk11-downloads.html (Oracle JDK 11)
 - https://aws.amazon.com/de/corretto/ (Amazon Corretto)

**Comment by TNG-China** [comment]
@realPanamo @derklaro 
Thank you! Now I can run it when I reinstall JDK.
