### ISSUE TITLE
Server updates

### ISSUE THREAD

**Issue by robertschuck** [CloudNetService/CloudNet-v3#24]
Every second a server is updated, even if nothing has really changed. This may cause performance problems with many servers. Therefore I would only trigger the events if something really changed on the server (player, game status etc.). The other data about the server like memory usage will probably not be required every second.

**Comment by 4zuree** [comment]
Seems like a feasible option. This needs more research though due to insufficient documentation. Implementing this could break a mechanism which depends on regular updates. So, proceeding here is to be done with caution.

Can you provide us/me with code snippets where this is being done?

**Comment by McRuben** [comment]
I think we can remove those updates, it seems like they are only used for the signs, where I don't see anyone wanting to display the cpu usage or thread count of a server on a sign. Why would a user want to know the cpu usage or thread count of a server?

**Comment by McRuben** [comment]
Here is where the ServiceInfo is updated (every 5 seconds): https://github.com/CloudNetService/CloudNet-v3/blob/development/cloudnet-wrapper-jvm/src/main/java/de/dytanic/cloudnet/wrapper/Wrapper.java#L2283-L2286
