### ISSUE TITLE
autoSlot counting too much

### ISSUE THREAD

**Issue by finki70** [CloudNetService/CloudNet-v3#244]
**Describe the bug**<br>
autoslot is counting higher as maxPlayers

**Steps for reproducing**<br>
1. set maxPlayers to 1
2. set "autoSlot": true & "autoSlotMaxPlayersDistance": 1,
3. Connect to the proxy
4. See error in the serverlist

**Expected behavior**<br>
autoslot should only count up to the maxPlayers-Value

**Please provide us information about your environment and used assets**

 System specs: 6CPU 16GB RAM
 OS: Debian
 Version: Cloudnet 3.2.2 RELEASE

**Comment by derklaro** [comment]
I think it's expected to count higher as the max player count

**Comment by finki70** [comment]
> I think it's expected to count higher as the max player count

hmmm i dont get the intention for displaying more slots then offered

**Comment by juliarn** [comment]
When autoSlot enabled, there won't be any limit for players. The intention of autoSlot is, that the maxPlayers automatically adapt to the players online.

**Comment by finki70** [comment]
So why can't I connect to the server then?

**Comment by juliarn** [comment]
What happens when you connect to the server?

**Comment by finki70** [comment]
I get a "failed to connect to the server" - Error and it displays my "player-login-full-server"- message

**Comment by juliarn** [comment]
Yeah, I just saw this in the code. Idk why it has been done like this, we might change this.

**Comment by juliarn** [comment]
@derrop what is your opinion on this? Should autoSlot make space for players without limit or should the configured maxPlayers still have an effect?

**Comment by derklaro** [comment]
I mean you can count up until you reach another defined Max Auto slots variable or something like this

**Comment by finki70** [comment]
Why should I define 2 variables when I could use one? :c

**Comment by derklaro** [comment]
The main idea was that you can set the maxPlayers of the proxy. If you have autoslot enabled you can set the maxAutoSlotCount higher than the maxPlayers and the max player count will increase with the autoSlots until it's at the maxAutoSlotCount 🤷‍♂

**Comment by juliarn** [comment]
AutoSlot will now count up until the maxPlayers are reached. Thx for your report
