### ISSUE TITLE
Time to make some changes to CloudNet's codebase

### ISSUE THREAD

**Issue by ghost** [CloudNetService/CloudNet-v3#25]
So, I "analyzed" CloudNet's code and oh boy, a lot of work needs to be done. By work I mean actual code and performance optimization, debugging etc.

Most things can probably be done using IntelliJ's advanced refactoring tools, like searching for something and replacing it, but there's also stuff on the list which needs to be done by hand. 

Pending:
- [x] *[approved]* Use builders where applicable
- [ ] *[approved]* Create data classes where applicable
- [ ] *[wip]* Replace pure string concats `abc += "def"` with StringBuilder appends 
- [x] *[approved]* Replace `java.io` classes with `java.nio` classes where applicable, might require `@Deprecated` declarations
- [x] *[approved]* Some abstract classes and interfaces are waayyy too fat. Requires separation. Might require `@Deprecated` declarations
- [ ] *[approved]* Return `Collection<?>` types instead of `List<?>`, `Set<?>` or any other extending interface or class of `Collection`. Might require `@Deprecated` declarations
- [ ] *[approved]* **Use lazy type initialization. (Let a field be initialized by a getter or setter, if the field is null. A lot of stuff in CloudNet might not be needed by anyone or anything)**

Work in progress:
- [x] Replace inline statements with block statements 
- [x] Calls to functions located in own class should use the `this.` accessor
- [x] Calls to functions located in super class should use the `super.` accessor **ONLY IF** the function is not overridden by the child class
- [x] Try catch blocks shouldn't silently dispose any exceptions/throwables. (Re-)Throw, print or log them
- [x] Parameter validations shouldn't silently dispose any exceptions. (Re-)Throw, print or log them
- [x] Re-arrange fields correctly
- [x] Re-arrange functions correctly
- [x] Separate chained field declarations
- [x] Validate the state of parameters (Is the int negative?, is the string blank even though it shouldn't be?, is the passed varargs array empty?)
- [x] Validate the parameter for null
- [x] Use Guava's Preconditions instead of own validation class

Done:
- [x] Lombok should not be used in such complex application. The only thing Lombok could be used for is generating `#equals()`, `#hashCode()` and `#toString()`. Using `@Getter`, `@Setter` and any other Lombok annotations is highly discouraged blurs a class' logic

*More to come*

**Comment by byRoadrunner** [comment]
First of all thank you for this "analysis" of CloudNet, we´ll look into these issues and will do our best to fix them.
Second of all, maybe a bit offtopic, but the bot can only distinguish between a feature request, bug or question. So I think the label was okay :).

**Comment by 4zuree** [comment]
# Offtopic: 
Well, create own labels. Since you guys are responding to every single issue, you probably might want to assign your own labels and manage them by yourself.

**Comment by realPanamo** [comment]
I only disagree with "Use Guava's Preconditions instead of own validation class", because it would mean to use Guava as a dependency, just for one class. The other things are all fine, if there no breaking api changes. As you already mentioned, the deprecate the old method. I would start with fixing the small things and first not modifying the api that much.

**Comment by 4zuree** [comment]
Guava isn't actually that big. Including Guava would mean to add 2.6 of megabytes but that's it. And if Guava is included, way more code optimization could be done with Guava. I don't know yet, where this would be the case but I think there are some cases where using Guava would pay off.

If you're worrying about actual file size of CloudNet then you should consider optimizing the Maven module 'cloudnet-modules' first, which is approximately 100 megabytes of file size. Furthermore, you can strip away all non used classes of Guava, which means Maven would only shade Guava's classes which used by CloudNet. Everything else is being discarded by Maven.

**Comment by realPanamo** [comment]
I like Guava and also the Preconditions, but I still don't think Guava is necessary just to do something which is already implemented. If there's another use-case for Guava, adding it and replacing everything with the Preconditions is acceptable.

**Comment by 4zuree** [comment]
Redundant classes and packages - provided by Guava:
- Package `concurrent` in `de.dytanic.cloudnet.common`
- Package `collection` in `de.dytanic.cloudnet.common`, excluding `Pair` and `Triple`
- Package `registry` in `de.dytanic.cloudnet.common`, Guava provides services

And a lot more. I actually don't want to crawl through the complete source code because it would cost me ages to list everything where Guava would be applicable. 

I **promise** you, including Guava is definitely a "win" for CloudNet! Most of the stuff of   `de.dytanic.cloudnet.common` is totally redundant because Guava provides most of the stuff.

If you're really concerned about file size: You can configure Maven and the Guava dependency in such way that Maven only shades the classes of Guava needed or referenced by/in CloudNet.

**Comment by realPanamo** [comment]
I think these things are all there because they should replace the Guava stuff. I think there is no need to implement Guava, because of this replacements, but if you want to do it, I won't do anything against it.

**Comment by 4zuree** [comment]
Not using Guava would mean, that we'd have to maintain all of our own commons. Technically speaking, we're maintaining something which Google's maintaining in their own library and probably more efficient. Re-inventing the wheel isn't the best imho.

**Comment by 4zuree** [comment]
Experiencing some delay in resolving the mentioned issues due to real life complications. Some of them are expected to be resolved by the end of this weekend. Thank you for your patience.

**Comment by 4zuree** [comment]
Additionaly, I have noticed that the class `BungeeCloudNetCloudPermissionsPlayerListener` uses reflection invocations to gain access to `ProxiedPlayer#getUniqueId()`, from a `ProxiedPlayer` instance of `PlayerDisconnectEvent` , even though `#getUniqueId()` is exposed through an interface and thus 100% **public**. Why's that done like this?

**Comment by realPanamo** [comment]
Not documented, no one knows.

**Comment by 4zuree** [comment]
So I guess we're free to use direct method invocations instead of calling it through reflection invocations. What the heck. Mind fixing this while I'm working on the other issues?

**Comment by realPanamo** [comment]
No, you can do it.

**Comment by 4zuree** [comment]
Gotcha.

**Comment by CraftCoderr** [comment]
Relative to Lombok, what you think about ** var ** and ** val ** keywords?
And have you any other reasons to delombok whole project except of controversial "lombok annotations highly discouraged blurs a class' logic" (especially for so harmless getter/setter annotations)?

**Comment by CraftCoderr** [comment]
Do you agree that interfaces shouldn't be named starting with `I`? Can it be added to ToDo list?

**Comment by McRuben** [comment]
Well, we can't just rename every interface starting with an I. Those aren't only used in CloudNet itself, but the users can also use them.

**Comment by realPanamo** [comment]
Yes, we don't like these names too and new interfaces won't be called like that, but changing this without causing breaking changes will be very much work and I think it's not worth it.

**Comment by CraftCoderr** [comment]
You can create interfaces without `I`, extends it with original "`I`" interfaces, which now can be marked as Deprecated. And then someday they will be permanently deleted.

**Comment by realPanamo** [comment]
Hm no, some impls of the interfaces are called like the interface without the I. And I still think that's not really worth it.

**Comment by derrop** [comment]
So I just did `Calls to functions located in own class should use the this. accessor`, but I don't agree with `Calls to functions located in super class should use the super. accessor ONLY IF the function is not overridden by the child class`. If you accidentally use `super` even if the method is overridden, this might cause issues.

**Comment by derklaro** [comment]
Just use 'this.' accessor there too

**Comment by derklaro** [comment]
All of the really necassary things are done. We did a lot of optimizations to the code and everything that is still in there will be replaced in a later step. Closing as we do the optimizations no longer based on this issue.
