### ISSUE TITLE
ClounDet NPC

### ISSUE THREAD

**Issue by LoToRTv** [CloudNetService/CloudNet-v3#260]
Hello, it could be added block and command from motd all of them minigame use motd like in game waitng atd 

1:
motd:  "WAITING "
material: "LIME_DYE",
displayName: "§a%name%"
connect: true
command: ""
            " ",
            "§8● §e%state%",
            "§8● §7%online_players%§8/§7%max_players%",
            "§8● §7%motd%"
2:
motd:  "IN_GAME "
material: "RED_DYE",
displayName: "§a%name%"
connect: false
command: "say server in game!"
            " ",
            "§8● §e%state%",
            "§8● §7%online_players%§8/§7%max_players%",
            "§8● §7%motd%"

**Comment by juliarn** [comment]
I don't really get what you mean. And ingame servers won't be displayed in the NPC inventory

**Comment by LoToRTv** [comment]
how will Cloudnet know server in game ?

**Comment by juliarn** [comment]
Servers can set this via the motd or api
