### ISSUE TITLE
Module CloudPerms deaktivieren

### ISSUE THREAD

**Issue by TricityGaming** [CloudNetService/CloudNet-v3#261]
Ich möchte gerne für ein Projekt verschiedene Gruppen über ein Spigot Plugin wechseln können, da aber die Permissions von CloudPerms nicht über Spigot veränderbar sind per Command durch die Konsole würde ich gerne ein anderes Permissions System nutzen. CloudPerms lässt sich aber nicht abschalten, das einzige was ich finde ist die config im Modules Ordner. Wenn ich da enabled auf false stelle und alles über das LuckPerms Plugin im BungeeCord laufen lasse kann ich z.B. trotzdem nicht joinen (Maintenance Permission wird nicht erkannt).

Gibt es da eine Lösung?

**Comment by juliarn** [comment]
Hey,
tatsächlich funktioniert die Maintenance permission auf grund von BungeeCords Aufbau nur bei CloudPerms.
Du kannst CloudPerms aber nur auf bestimmten Gruppen deaktivieren, dafür gibt es die Option "excludedGroups" in der Config des Moduls.

**Comment by TricityGaming** [comment]
Alles klar danke, schönen Tag noch.

**Comment by TricityGaming** [comment]
So ich habs jetzt probiert, aus irgendeinem Grund werden die Permissions des anderen Permission Systems nicht erkannt. Kann das an CloudNet liegen oder kann es technisch nur an dem Plugin selbst liegen? Und wenn es an CloudNet liegt wie deaktiviere ich es so dass das jeweilige andere Permission System erkannt wird. Habs mit LuckPerms (BungeeCord) und Luckperms (Spigot) probiert. Die config.json des CloudPerms Modules sieht folgend aus:
`{
  "enabled": false,
  "excludedGroups": [
    "Admin"
  ]
}`

**Comment by juliarn** [comment]
Das excludedGroups bezieht sich nicht auf die PermissionGruppen, sondern auch die Gruppen in der groups.json.
Wenn man "Lobby" einträgt, wird CloudPerms dann auf dem Lobby-1 Server z.B. nicht aktiviert,
Aktuell hast du aber CloudPerms komplett ausgeschaltet.
Permissions funktionieren meistens deswegen nicht, weil noch ein zweites PermissionsSystem läuft.
Stell sicher, dass nur eins läuft.

**Comment by TricityGaming** [comment]
Danke ich schau mal

**Comment by TricityGaming** [comment]
Obwohl es aber komplett ausgeschaltet ist scheint es weiterhin aktiviert zu sein. Wenn ich mir die CloudPerms Gruppe Admin wegnehme habe ich keine Permission mehr. Eigentlich sollte ich ja unabhängig davon ob ich jetzt in der Admin Gruppe bin keine Permission haben. Bei anderen Rängen ist das genauso.

**Comment by juliarn** [comment]
Hast du die Cloud reloadet und den entsprechenden Server neugestartet? Sonst schau mal, ob CloudPerms vllt noch irgendwo im Template ist.

**Comment by TricityGaming** [comment]
Ich denke mal die Cloud Perms Plugins müssen logischerweise aus dem plugins Ordner? Habs ganz vergessen da alle Server static sind. Dann machts auch Sinn das es nach dem neustart natürlich nichts gebracht hat.

**Comment by juliarn** [comment]
Jo
