### ISSUE TITLE
Missing API Documentation

### ISSUE THREAD

**Issue by Flaflo** [CloudNetService/CloudNet-v3#274]
**Please describe the proposed feature**
This Project provides a large API. But it lacks documentation almost entirely. This makes almost impossible to create any Addons or Communication with the CloudNet without studying the code. It takes a hell lot of time to get through all of that until you find something that you need or you searched for. Please. For gods sake. Change this.
I realy appreciate your work and its huge! But missing documentation just throws me back everytime.
Autogenerated JavaDoc is just not enough.

**Comment by juliarn** [comment]
I agree, we are trying to add more documentation on every update.
Please also see the cloudnet-examples module for help with the API.

**Comment by Flaflo** [comment]
The examples are sadly not deep enough. Especially when it comes to communication between a Bukkit Plugin and a custom Module on the cloud side. Things I am also missing is: How to correctly create a module and what API Drivers are for Bukkit and for Module or are both crosscompatible? Things like that.

**Comment by juliarn** [comment]
The CloudNetDriver can be used for both plugins and modules.
If more specific features are needed, you can use the cloudnet dependency for modules and the wrapper dependency for plugins.
The examples contain creation of modules.
For communication between the modules and plugins, you can use the ChannelMessageReceiveEvent and to the CloudNetDriver#getMessenger

**Comment by Flaflo** [comment]
I saw the messenger but my problem with it is, that to my understandings it is sending them globally through channels. And if i have multiple hub servers for example and one requests player data, how are both sides meant to distinguish each from another. when the server sends a response?

**Comment by juliarn** [comment]
For queries, I would use Callable packets, like it's done here: https://github.com/CloudNetService/CloudNet-v3/blob/8ef0d7687d4f79c0e80bf94668dd5a2f0e639b28/cloudnet-modules/cloudnet-npcs/src/main/java/eu/cloudnetservice/cloudnet/ext/npcs/AbstractNPCManagement.java#L185 
You can then use the NetworkChannelReceiveCallablePacketEvent like it's done here: https://github.com/CloudNetService/CloudNet-v3/blob/8ef0d7687d4f79c0e80bf94668dd5a2f0e639b28/cloudnet-modules/cloudnet-npcs/src/main/java/eu/cloudnetservice/cloudnet/ext/npcs/node/listener/CloudNetNPCMessageListener.java#L36

For the messenger, you can target specific services which the message should go to.

**Comment by Flaflo** [comment]
Is it possible to get in touch with you over Discord or something similiar?

**Comment by derklaro** [comment]
Of course: https://discord.gg/3nJuWz :)

**Comment by juliarn** [comment]
Sure, you can join our discord for CloudNet application and development support: https://discord.gg/357F5wH
