### ISSUE TITLE
Rewrite in rust

### ISSUE THREAD

**Issue by deeprobin** [CloudNetService/CloudNet-v3#275]
**Description of the new feature:**

Use rust

**Reasons for inclusion into the CloudNet code base:**

Memory safety

**Planned audience:**

Those who benefit from the performance boost

**Comment by juliarn** [comment]
I understand your idea, but the performance and memory safety benefits are in no comparison to the benefits Java gives us.
1. The most MC server softwares are written in Java, so plugins need to be in java too. We would be forced to implement the protocol in both Java and Rust.
2. The most in the MC community know java and are able to extend the cloud with modules written in Java.

Furthermore derrop and I don't know Rust and we want to avoid rewrites and breaking changes.

**Comment by byRoadrunner** [comment]
Also you deleted the following parts of the issue template which are especially for such changes which you requested very important.

```
Preview of code and documentation:

Additional context:
```

**Comment by tobimori** [comment]
Cry me a river.

**Comment by derklaro** [comment]
Please only topic related comments

**Comment by juliarn** [comment]
I think I can close this now :)
