### ISSUE TITLE
getOnlinePlayers not working on Bungee

### ISSUE THREAD

**Issue by 0xLyptox** [CloudNetService/CloudNet-v3#278]
**Description of the bug:**
When you call the **getOnlinePlayers**-Function of the IPlayerManager-Class, you will get an Error on Bungee.

**Steps to reproduce this bug:**

1. Create a Bungee Plugin
2. Call `CloudNetDriver.getInstance().getServicesRegistry().getFirstService(IPlayerManager).getOnlinePlayers()`

Steps to reproduce the exception:
1. Call `CloudNetDriver.getInstance().getServicesRegistry().getFirstService(IPlayerManager).getOnlinePlayers()`
2. See exception (NullPointerException)

**Expected behavior:**

It should return a Collection of the CloudPlayers

**Screenshots:**
![grafik](https://user-images.githubusercontent.com/51520651/82958236-3f698b80-9fb5-11ea-8ebd-159a26a17fad.png)

**Environment and used hardware:**

 System specifications: n/a
 OS: Linux
 Version: v3.3

**Additional context (optional):**
I've made sure, that the CloudNet-Bridge Plugin has been depended into the bungee.yml

**Comment by derklaro** [comment]
Please also specify the exception (complete stacktrace)

**Comment by 0xLyptox** [comment]
![grafik](https://user-images.githubusercontent.com/51520651/83014889-cce1c580-a01f-11ea-9d3c-ab0f344f2de4.png)
Line 52 is the `CloudNetDriver.getInstance().getServicesRegistry().getFirstService(IPlayerManager).getOnlinePlayers()`

**Comment by derklaro** [comment]
Can you check if the IPlayerManager is null?

**Comment by 0xLyptox** [comment]
It wasn't I went to each Method and only getOnlinePlayers was null

**Comment by derrop** [comment]
I have just tested the getOnlinePlayers method in onEnable on Bungee, everything works fine.

**Comment by 0xLyptox** [comment]
But what could be the issue

**Comment by derrop** [comment]
`depends: [CloudNet-Bridge]` in the bungee.yml/plugin.yml? (depend on Bukkit, depends on Bungee)

**Comment by 0xLyptox** [comment]
Yes, but it's anyway

**Comment by 0xLyptox** [comment]
TitanNet, MCCommons, CloudNet-Bridge, CloudNet-CloudPerms, acl-handler, protocolize-plugin, CloudNet-SyncProxy has been loaded on the Bungee

**Comment by 0xLyptox** [comment]
TitanNet is under CloudNet-Bridge, so it's not because of the missing of the depend

**Comment by 0xLyptox** [comment]
![grafik](https://user-images.githubusercontent.com/51520651/83018126-0d900d80-a025-11ea-802d-4131c85300d5.png)

**Comment by 0xLyptox** [comment]
I've got it. It was the Shadow Plugin from Gradle. I shouldn't shadow the Bridge-Plugin into the Bungee Plugin
