### ISSUE TITLE
Add Docker Support

### ISSUE THREAD

**Issue by ArnaudLier** [CloudNetService/CloudNet-v3#284]
**Description of the new feature:**

Add Docker support with containers.

**Reasons for inclusion into the CloudNet code base:**

Because Docker is cool

**Planned audience:**

Developers, server administrators

**Comment by TheMeinerLP** [comment]
The idea is good, but we have the problem that CloudNet as a node has too many threads. If I'm not mistaken.

**Comment by 0utplay** [comment]
Added in #572
