### ISSUE TITLE
MOTD in CloudNPCs not encoded in UTF8

### ISSUE THREAD

**Issue by ZeProf2Code** [CloudNetService/CloudNet-v3#285]
**Description of the bug:**

The MOTD in CloudNPCs is not encoded in UTF8 which results in this:
![image](https://user-images.githubusercontent.com/32982428/84500324-96a97480-acb4-11ea-9379-08a21e983ab4.png)

**Steps to reproduce this bug:**

1. Put the character 'É' for example in the MOTD using '\u00C9'
2. Click on a NPC in game
3. See that the character is not encoded properly.

**Expected behavior:**

Character is encoded properly.

**Screenshots:**

![image](https://user-images.githubusercontent.com/32982428/84500423-cc4e5d80-acb4-11ea-9ba6-1d930b4cba5f.png)
![image](https://user-images.githubusercontent.com/32982428/84500438-d4a69880-acb4-11ea-9421-aded7b1aadc1.png)

**Environment and used hardware:**
 
 System specifications: CPU= 4 cores of Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz and 8Gb 2333Mhz of memory
 OS: Linux | Ubuntu 20.04
 Version: CloudNet Latest

**Comment by juliarn** [comment]
This is more likely caused by Minecraft reading the server.properties file in another encoding than UTF-8.
Displaying this char should be no issue when setting the motd with a plugin via the ServerListPingEvent.
