### ISSUE TITLE
Tips depend on target shell and yours is unknown. Add a shebang.

### ISSUE THREAD

**Issue by byRoadrunner** [CloudNetService/CloudNet-v3#292]
#### Currently on:
+ **Commit**:  329c21f03a9e668e1ffc2eb5b575c007c533ba44
+ **File**:    [.template/start.sh](https://github.com/CloudNetService/CloudNet-v3/blob/329c21f03a9e668e1ffc2eb5b575c007c533ba44/.template/start.sh)
+ **LineNum**: [1](https://github.com/CloudNetService/CloudNet-v3/blob/329c21f03a9e668e1ffc2eb5b575c007c533ba44/.template/start.sh#L1)

**Comment by derklaro** [comment]
# Close
