### ISSUE TITLE
Temp services should not use special characters (replace # with _)

### ISSUE THREAD

**Issue by Meldiron** [CloudNetService/CloudNet-v3#30]
**Describe the bug**<br>
Some plugins doesnt work due to # character for temp servers (the path is `/root/CloudNet/temp/services/Economy-Hub-1#34595385-69f1-4da4-ac4d-3fa90e1d3b78/plugins`)

**Steps for reproducing**<br>
Cant share jar of plugins but they throw errors like:
`http://java.io.FileNotFoundException: /root/CloudNet/temp/services/Economy-Hub-1%23804f3165-9993-4484-a270-c0846d02de69/plugins/VillagerBlock.jar (No such file or directory).`

**Expected behavior**<br>
Not throwing errors. You can solve this by not using # in the folder name but some other character like _

**Please provide us information about your environment and used assets**
Tried both Linux Debian, Windows 10. Anyway, problem is in plugin not cloudnet, cloudnet just need to change from # in folder name to something else.

**Comment by realPanamo** [comment]
Fixed by 2bea88887c1fd74bdbaf032ff16f0b4e6f8dd8f0
