### ISSUE TITLE
Nukkit Link

### ISSUE THREAD

**Issue by MenschenToaster** [CloudNetService/CloudNet-v3#302]
**Description of the bug:**

The link in the readme(or maybe other places) redirects to https://github.com/NukkitX/Nukkit but Nukkit is now a part of the CloudburstMC Organisation(I think the Bedrock Cubecraft server started the Organisation)!

The Link should be https://github.com/CloudburstMC/Nukkit now.
Github redirects the link but I think that could change.

**Comment by juliarn** [comment]
Done in d6dfc9a, thanks for the hint
