### ISSUE TITLE
NPCs not being spawned when quickly moving in and out of the range

### ISSUE THREAD

**Issue by derrop** [CloudNetService/CloudNet-v3#307]
**Description of the bug:**

In Minecraft, players are not being spawned when they are not in the tablist. When a player moves in, directly out and again into the range where NPCs will be spawned, they will not be spawned because they are not added to the tablist.

**Expected behavior:**

Before addinf the players twice to the tablist and removing them too early, they should not be added twice and the timer for removal should be restarted.

**Comment by derklaro** [comment]
I think this is an issue of juliarn/NPC-Lib, not cloudnet (moved it to that repository)
