### ISSUE TITLE
A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@5408857f

### ISSUE THREAD

**Issue by DxsSucuk** [CloudNetService/CloudNet-v3#311]
Everytime i try to join im joining for like 10 sec

If im using normal Bungeecord(no fork) im getting the error A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@5408857f java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
but im still connecting

start CloudNet try to join logging in error in the console 10 secs later kick

**Comment by derrop** [comment]
That error means that no fallback server can be found, is the lobby running?

**Comment by DxsSucuk** [comment]
yes it is

**Comment by derrop** [comment]
Then please send the link that you get from the `paste all` command

**Comment by DxsSucuk** [comment]
https://hasteb.in/onetesew

**Comment by derrop** [comment]
You don't have any fallbacks configured in the bridge module, the default config with fallbacks for the group `Proxy` to `Lobby` looks like this: https://pastebin.com/qEVt9ndL

**Comment by DxsSucuk** [comment]
oh an error in CloudNET Bridge because of misconfiguration?

**Comment by derrop** [comment]
Yes, the file will be reset when there is a syntactical error in it

**Comment by DxsSucuk** [comment]
okay thx
