### ISSUE TITLE
Domains verwenden anstatt IP

### ISSUE THREAD

**Issue by DanteDFF** [CloudNetService/CloudNet-v3#319]
Guten Tag,
Ich würde gerne ein Feature haben das ermöglicht, dass ich über mehrere nodes netzwerk übergreifend ansteuern kann, dass heißt das man anstatt einer IP eine Domain eintragen kann als NOde

**Comment by derrop** [comment]
Das Template gibt es nicht ohne Grund, also halte dich bitte auch daran.
