### ISSUE TITLE
Remove useless timeout

### ISSUE THREAD

**Issue by PierreSchwang** [CloudNetService/CloudNet-v3#326]
I don't know what the reason for this Thread#sleep is, but imo it makes no sense. I think it would be better to remove this "feature"
https://github.com/CloudNetService/CloudNet-v3/blob/329c21f03a9e668e1ffc2eb5b575c007c533ba44/cloudnet-launcher/src/main/java/de/dytanic/cloudnet/launcher/CloudNetLauncher.java#L94

**Comment by juliarn** [comment]
It's not that important, the idea was that the user can see, what the launcher does and which version it is about to start.

**Comment by PierreSchwang** [comment]
I mean, that's the whole point of the "me" command, or?
I like my applications fast, and 3 seconds just for the "show" - I dont know

**Comment by derklaro** [comment]
Fair enough to remove it - nobody cares about it

**Comment by 0utplay** [comment]
I think this can be closed now. It was removed [here](https://github.com/CloudNetService/CloudNet-v3/commit/ee582cbbaaf15b3aae2e0cd6bb3236e7ceb195eb)
