### ISSUE TITLE
Players remain online

### ISSUE THREAD

**Issue by robertschuck** [CloudNetService/CloudNet-v3#33]
**Describe the bug**<br>
When you stop a proxy with players it sometimes happens that the players are still marked as online by the cloud.

**Steps for reproducing**<br>

```
Steps to reproduce the behavior:
1. Start Proxy
2. Join Proxy
3. Stop Proxy via /end
4. check playerstatus via console command or api
```
```
Steps to reproduce the exception:
1. -


**Expected behavior**
The player is displayed as Offline


**Screenshots**
-


**Please provide us information about your environment and used assets**
 System specs: 8 GB RAM, 2vCores, 80 GB SSD
 OS: centOS 7
 Version:  v3.0.0 Tsunami RELEASE  (https://discordapp.com/channels/325362837184577536/536594705643864093/580456188991242241)



**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by robertschuck** [comment]
Apparently also happens sometimes during normal logout.

**Comment by realPanamo** [comment]
I'm not able to reproduce the bug, after stopping the proxy the cloud seems to recognize that the player is gone.

**Comment by KlaroYT** [comment]
Sometimes BungeeCord don't calls the DisconnectEvent properly. This may cause the problem.

**Comment by realPanamo** [comment]
Never experienced this, might be caused by bungeecord etc.
