### ISSUE TITLE
Add PlaceholderAPI support

### ISSUE THREAD

**Issue by robertschuck** [CloudNetService/CloudNet-v3#331]

**Comment by derklaro** [comment]
Can someone please give feedback if this is still needed? In my opinion PlaceholderAPI support is unnessacary and can never provide full support for all placeholders someone needs or these placeholders have performance issues because of a lot of node requests.

Cc: @juliarn , @0utplay

**Comment by 0utplay** [comment]
I also think that the PlaceholderAPI for such a large project is not only a big effort, but also cannot be implemented continuously.

**Comment by Sarsum** [comment]
Well, we might not be able to implement continuously every new placeholder, but in my opinion we should implement at least the very basic placeholders because many users requested it (and probably will request it in the future).
