### ISSUE TITLE
Is there a webinterface for Cloudnet 3?

### ISSUE THREAD

**Issue by RandomModderJDK** [CloudNetService/CloudNet-v3#368]
We just installed our entire System with Cloudnet-v3 and would like to have a webinterface. Is there anyone out there?

**Comment by juliarn** [comment]
Hey, we don't provide an official webinterface for CloudNet and as far as I know, there aren't unofficial webinterfaces too.

**Comment by RandomModderJDK** [comment]
Ok, what not is, can become.
