### ISSUE TITLE
NPE in NodeCloudNetModule

### ISSUE THREAD

**Issue by robertschuck** [CloudNetService/CloudNet-v3#37]
**Describe the bug**<br>
If you use CloudPermissionsPermissionManagement in a NodeCloudNetModule, the instance (getInstance()) is null.

**Steps for reproducing**<br>
```
Steps to reproduce the behavior:
1. Create NodeCloudNetModule
2. Get eg. PermissionUser (CloudPermissionsPermissionManagement.getInstance().getUser(this.uuid))
3. See npe error
```

**Additional context**<br>
How to bypass it without changing the cloud source code:
```
if (CloudPermissionsPermissionManagement.getInstance() == null) 
  new CloudPermissionsPermissionManagement();
```

**Comment by 4zuree** [comment]
That's due to Lombok's Getter annotation which doesn't provide **proper** lazy initialization. Lombok does ship with lazy value initialization but with a way more complex behavior/logic. Consider this as done.

**Comment by 4zuree** [comment]
FYI: The issue has been fixed by commit https://github.com/CloudNetService/CloudNet-v3/pull/39/commits/a8dfe4554961096fd30b6b0aa80d2705cda4b86f; Issue remains open until the `development` branch gets merged into the `master` branch.
