### ISSUE TITLE
Server slots get out of sync

### ISSUE THREAD

**Issue by titivermeesch** [CloudNetService/CloudNet-v3#384]
**Description of the bug:**

When the number of slots of a server get changed, the actual service information is not updated accordingly. Which reflects in the service only showing the initial server slots and not the actual slots

**Steps to reproduce this bug:**

1. Launch a server with 100 slots
2. Programmatically change these slots to whatever you like

**Expected behavior:**

The slots shown in the service information should show the actual slots

**Environment and used hardware:**

 System specifications: Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (18C/36T)
 OS: Ubuntu 
 Version: 20.04.1 LTS

**Comment by derklaro** [comment]
How do you update the slots?

**Comment by titivermeesch** [comment]
Like this:

```java
public static void changeSlots(int slots) {
        try {
            Method serverGetHandle = ReallyAPI.getReallyAPI().getServer().getClass().getDeclaredMethod("getHandle");
            Object playerList = serverGetHandle.invoke(ReallyAPI.getReallyAPI().getServer());
            Field maxPlayersField = playerList.getClass().getSuperclass().getDeclaredField("maxPlayers");

            maxPlayersField.setAccessible(true);
            maxPlayersField.set(playerList, slots);
        } catch (ReflectiveOperationException e) {
            e.printStackTrace();
        }
    }
```

**Comment by einrobin** [comment]
There is no way for us to detect this change, you have to either use the CloudNet method or as supposed by Bukkit the ServerListPingEvent.

**Comment by derklaro** [comment]
That does not look like a supported api at all, so there is not much we can do. You can change it in cloudnet internally by using https://github.com/CloudNetService/CloudNet-v3/blob/master/cloudnet-modules/cloudnet-bridge/src/main/java/de/dytanic/cloudnet/ext/bridge/bukkit/BukkitCloudNetHelper.java#L195

**Comment by titivermeesch** [comment]
Ok thanks, I'll have a look to change it with the CN methods
