### ISSUE TITLE
CloudNet Repos hosting org.spigotmc:spigot-api, org.spigotmc:spigot, and org.spigotmc:minecraft-server

### ISSUE THREAD

**Issue by A248** [CloudNetService/CloudNet-v3#394]
The CloudNet ~~3~~2 repository is hosting the Spigot server jar, as well as the vanilla server jar:
https://cloudnetservice.eu/repositories/org/spigotmc/

To my knowledge, the spigot jar cannot be directly distributed in this way without violating the CraftBukkit DMCA. The `org.spigotmc:minecraft-server` jar, which is the vanilla server, is also in the same repo, and its distribution is too is legally unsound. Both jars contain proprietary software by Mojang.

I would strongly recommend you remove these dubious jars from your public repository.

Disclaimer: I am not a lawyer. My words are not legal advice.

**Comment by A248** [comment]
I realized cloudnetservice.eu is the CloudNet 2 repository. However, the CloudNet 3 repository is hosting `org.spigotmc:spigot-api` which is not CloudNet's namespace to publish.

https://repo.cloudnetservice.eu/repository/releases/org/spigotmc/spigot-api/

**Comment by juliarn** [comment]
We removed all "illegal" and inappropriate dependencies from our repos, thank you for the issue.
