### ISSUE TITLE
Don't use/call the Object::finalize method

### ISSUE THREAD

**Issue by Ingrim4** [CloudNetService/CloudNet-v3#4]
The way the Object::finalize method is used in this project is not its intended way, according to [Javadoc](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#finalize--) it is:

> Called by the garbage collector on an object when garbage collection determines that there are no more references to the object.

I would recommend removing these lines since they are obsolete (there could be even more these are just the ones I found while looking through the source code):

https://github.com/CloudNetService/CloudNet-v3/blob/1a255441f7832a461253634a13a605d370fddf4f/cloudnet-common/src/main/java/de/dytanic/cloudnet/common/io/FileUtils.java#L91
https://github.com/CloudNetService/CloudNet-v3/blob/1a255441f7832a461253634a13a605d370fddf4f/cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/module/FinalizeURLClassLoader.java#L66
https://github.com/CloudNetService/CloudNet-v3/blob/1a255441f7832a461253634a13a605d370fddf4f/cloudnet-driver/src/main/java/de/dytanic/cloudnet/driver/network/protocol/Packet.java#L53

I also wouldn't recommend using the finalize​ method to clean up since in later [java versions](https://docs.oracle.com/javase/9/docs/api/java/lang/Object.html#finalize--) it's deprecated because:

> The finalization mechanism is inherently problematic. Finalization can lead to performance issues, deadlocks, and hangs. Errors in finalizers can lead to resource leaks; there is no way to cancel finalization if it is no longer necessary; and no ordering is specified among calls to finalize methods of different objects.

**Comment by realPanamo** [comment]
Fixed by 59a9e9d
