### ISSUE TITLE
reconnect to latest server 

### ISSUE THREAD

**Issue by lostINParadies** [CloudNetService/CloudNet-v3#400]
Description of the bug:

Hallo. Ich habe ein Problem mit dem Bridge Modul. Ich weiß auch nicht ob das unter bugs zählt.

Ich möchte gerne einstellen, dass man zum letzten Server gesendet wird, den man verlassen hat. Ich arbeite an einem Survival Netzwerk. Dort gibt es Die lobby, survival und farm. Nun möchte ich einstellen, dass wenn man aus der Farm sich ausloggt, dort auch wieder eingeloggt wird. Normal würde das mit force_default_server: false in config.yml bei bungeecord gehen. Nun weiß ich nicht, wie ich das mit cloudnet einstellen kann. Ist es Möglich Gruppen zu erstellen wie z.b

Gruppe 1: Lobby

Guppe 2: Farmwelt, Survival

Gruppe3: Testserver

Wenn ich in Gruppe 1 bin, werde ich auch wieder zu gruppe 1 reconnectet
Wenn ich Gruppe 2 bin, werde ich dort auch wieder reconnectet. Entweder auf survival oder auf Farmwelt, jenachdem wo ich mich ausgeloggt habe.

Bei Gruppe3 das Gleiche.

Ich das irgendwie möglich?

**Comment by Sarsum** [comment]
Moin, das ist erstmal kein Bug sondern eher ein nicht implementiertes Feature.
Auf Grund des MultiBungee-Systems müsste sich die Cloud dann ja den letzten Server zwischenspeichern.
Sofern du nur einen Bungeecord benutzt, kannst du das gerne mal mit der Option ausprobieren.

Wenn das nicht funtioniert, musst du das selber irgendwie umsetzen. Das BridgeModul bietet ja z.B. auch die Möglichkeit die Spieler mit einer besimmten Permission auf eine bestimmte Gruppe zu senden. Eventuell ist das damit für dich umsetzbar!

**Comment by lostINParadies** [comment]
Mit welcher Option meinst du?

**Comment by Sarsum** [comment]
In dem Bereich `bungeeFallbackConfigurations` in der Bridge Configuration (`modules/CloudNet-Bridge/config.json`) kannst du pro Proxy-Task verschiedene Fallbacks mit Permissions und Prioritäten einstellen. Das bietet ganz viele Möglichkeiten

**Comment by lostINParadies** [comment]
funktionieren die permissions nur über das cloudnet permissions system oder auch über plugins wie luckperms

**Comment by Sarsum** [comment]
Ob das mit anderen PermissionsSystemen auch geht kann ich dir leider nicht garantieren. Wir können ja schließlich nicht jedes Szenario testen.
Das musst du einfach ausprobieren, die Permission Abfrage ist ja ganz normal gemacht. Es kann aber sein, dass das zumindest beim ersten Fallback (beim Join) nicht funktioniert, weil die Permissions noch nicht geladen sind. Das Problem besteht zumindest bei der Wartungspermission, weil Bungeecord die anderen Permissions noch nicht geladen hat.

**Comment by lostINParadies** [comment]
Und ein Modul um den letzten Server zwischenzuspeichern von dem Spieler ist auch nicht in Zukunft vorgesehen?

**Comment by Sarsum** [comment]
Bisher noch nicht, aber du kannst gerne mit dem [Feature Request Template](https://github.com/CloudNetService/CloudNet-v3/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=) ein Issue dafür erstellen!
