### ISSUE TITLE
Reconnect to latest server 

### ISSUE THREAD

**Issue by lostINParadies** [CloudNetService/CloudNet-v3#402]
Die Möglichkeit ein Modul anzubieten, welches die Spieler zum letzten Server teleportiert. Das ist in Bungeecord normal möglich kann durch Clodunet aktuell nicht eingestellt werden. 

Vorteil wäre es für Survival/Dungeons Server. Ich habe für mein Netzwerk einen Bauserver und einen Farmserver und mehrere Dungeonsserver, weshalb ich Cloudnet auch so super finde. Die Möglichkeit einzustellen, ob man zum letzten Server geportet werden soll fände ich noch eine tolle Erweiterung

**Comment by derklaro** [comment]
Hallo. CloudNet Haupt-Aufgabe liegt momentan nicht auf solchen Funktionen. Ich würde dir empfehlen ein BungeeCord/Velocity Plugin zu erstellen welches dir diese Funktion anbietet.
