### ISSUE TITLE
Server bug?

### ISSUE THREAD

**Issue by chaosmann09** [CloudNetService/CloudNet-v3#405]
Ich habe über tasks setup 6BW server erstellt hab sie statisch gemacht das sie im service ordner sind und im service ordner sind aber nur 5Ordner für die bw.

Und deswegen kommt in der Konsole ein fehler das der server nicht starten kann weil er die start nicht findet.
Das komische ist aber ingame steht das der BW-6 server gestartet ist.

**Comment by chaosmann09** [comment]
Die version ist 1.8.8

**Comment by derklaro** [comment]
Can't reproduce for latest 3.4.
