### ISSUE TITLE
Simplenametags prefix color

### ISSUE THREAD

**Issue by realPanamo** [CloudNetService/CloudNet-v3#41]
**Describe the bug**<br>
In 1.13+, there should be a color property set in the scoreboard team of the player, this isn't the case currently, so the prefix isn't displayed properly.

**Comment by ProxieTV** [comment]
Commit of pull request #43 fixed this problem.
Now the color can be defined in the file permissions.json or via the command "perms group <group> setColor <color>.
Older MC versions are not affected by this.

After all this issue can be closed.
