### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by GamingKlex** [CloudNetService/CloudNet-v3#442]
**Description:**

After installing, or after starting CloudNet, connecting is impossible. The console is spammed with IndexOutOfBoundsExceptions and Minecraft can't even connect to the server.

**Steps to reproduce this bug:**

1. Install CloudNet
2. Ping the server
3. Look in the console

**Expected behavior:**

CloudNet would function normally and I could connect to the server.

**Environment and used hardware:**

 - OS: Windows 10
 - CPU: AMD Ryzen 7 2700, RAM: 16 GB (Giving 14 GB to CloudNet)
 - Version: 3.4.0-SNAPSHOT-b76c671
 (This also happens when using 3.3)

**Comment by 0utplay** [comment]
The problem is most likely that you are connecting to the cloud itself, what port are you joining to?

**Comment by GamingKlex** [comment]
I am connecting to the Proxy-Server Address, Port: 1410

**Comment by 0utplay** [comment]
That is the cloud port, the proxy should listen to 25565

**Comment by GamingKlex** [comment]
THANK YOU SO MUTCH, first I thought this was a bug due to Windows, but now it works when I connect to the Proxy! I waited over a half year, just to know that it's the wrong Port...
