### ISSUE TITLE
Multiple Storage-FTP connections are not possible

### ISSUE THREAD

**Issue by HollydaysJolo** [CloudNetService/CloudNet-v3#443]
**Description of the bug:**

If you specify several FTP templates in groups.json, it will only load one of the specified templates. It also happens that a task no longer starts 
`No application file found for CloudService [uniqueId = d03f6352-ca26-4fdc-877f-db619cc9e4db task = KnockIT name = KnockIT-1]! Please check the availability of this file.`.

**Steps to reproduce this bug:**

1. Create a Storage-FTP connection
2. Put multiple FTP templates in the `groups.json` *1
3. Restart CloudNet
4. Template will be not correct copied and servers not starting

**Expected behavior:**

All FTP templates should be copied correctly.

**Screenshots:**

![image](https://user-images.githubusercontent.com/65872875/115126919-eb073a00-9fd2-11eb-8f99-34837b0f2049.png)
*1

**Environment and used hardware:**

 System specifications: CPU = 8 Core `Common KVM processor`; RAM = 32GB
 OS: Linux
 Version: CloudNet 3.3

**Additional context (optional):**

**Comment by juliarn** [comment]
Hey, this has already been fixed here: 02c5ce801c548c9bb402b4604abaaeedfe8dedab
To use the fixed version, you can enable the option "use-snapshots" in the launcher.cnl file and restart CloudNet.
Thank you for your report.
