### ISSUE TITLE
CloudFlare Dns

### ISSUE THREAD

**Issue by oRIOnTx** [CloudNetService/CloudNet-v3#444]
Hi, when i try add multiple groups with subs like @, mc, play module always add first element of array

**Comment by Sarsum** [comment]
Hey there,
could you provide us a little more information? Like how your config looks like (without your private data and domain) and your Cloudnet version.

**Comment by derklaro** [comment]
Only the first one right? Can you please provide your version information?

**Comment by oRIOnTx** [comment]
https://pastebin.com/nqvA34kA

**Comment by oRIOnTx** [comment]
> Only the first one right? Can you please provide your version information?
https://pastebin.com/nqvA34kA . I use latest build v 3.3.0

**Comment by oRIOnTx** [comment]
![image](https://user-images.githubusercontent.com/40061096/115686557-fb683d80-a361-11eb-8642-9921605e7233.png)
I add small debug, and what we can see (I have multiple domains). Only first "We try add sub = @"

**Comment by oRIOnTx** [comment]
just remove **break** in **handle0** - it's fix that

**Comment by derklaro** [comment]
Yes i saw that already, but i'm not at home
