### ISSUE TITLE
Update player data

### ISSUE THREAD

**Issue by oRIOnTx** [CloudNetService/CloudNet-v3#453]
When we use property and call updateOnlinePlayer() we update data in database too. I think this function must update online online players right not offline?

**Comment by derklaro** [comment]
The online player is an offline player, so this behaviour is expected

**Comment by oRIOnTx** [comment]
> Интернет-игрок является автономным игроком, поэтому такое поведение является ожидаемым.

I know, but maybe add the functionality of asynchronous data update after disconnect player from server?

**Comment by derklaro** [comment]
I don't get the point of doing that. If we do it like this, that may cause data loss after a node/server crash for some reason.
