### ISSUE TITLE
Npc hand item

### ISSUE THREAD

**Issue by oRIOnTx** [CloudNetService/CloudNet-v3#454]
At new version minecraft 1.6.5 we have bug (players doesn't hide in tab)
![image](https://user-images.githubusercontent.com/40061096/116201847-9f772d80-a742-11eb-9a36-a6f3faacc9aa.png)
spawnedNPC can't give equipment. It's problem with **updated protocol**. 
https://pastebin.com/wACQq5nR

**Comment by 0utplay** [comment]
This is already fixed in the 3.4 Snapshot (development branch)

**Comment by oRIOnTx** [comment]
> This is already fixed in the 3.4 Snapshot (development branch)

ok)

**Comment by juliarn** [comment]
Yes, this is already fixed on the development branch. Thank you for reporting anyway.
