### ISSUE TITLE
Npc multi lines

### ISSUE THREAD

**Issue by oRIOnTx** [CloudNetService/CloudNet-v3#455]
Add custom lines above npc.

**Comment by 0utplay** [comment]
There already is an infoline for npcs.

Please use the issue / feature templates

**Comment by derklaro** [comment]
Multiple lines will be available in the next release. Thanks for your idea!

**Comment by oRIOnTx** [comment]
> Multiple lines will be available in the next release. Thanks for your idea!

Thanks)
