### ISSUE TITLE
SmartConfig: minNonFullServices ignored by cloud stop task

### ISSUE THREAD

**Issue by Sneakometer** [CloudNetService/CloudNet-v3#462]
When setting "minNonFullServices" to greater than 0, services stop and start in a loop with no players online.

CloudNet 3.4 snapshot
Java 8
Smartconfig:
```
  "properties": {
    "smartConfig": {
      "enabled": true,
      "priority": 10,
      "directTemplatesAndInclusionsSetup": true,
      "preparedServices": 0,
      "dynamicMemoryAllocation": false,
      "dynamicMemoryAllocationRange": 256,
      "percentOfPlayersToCheckShouldAutoStopTheServiceInFuture": 0,
      "autoStopTimeByUnusedServiceInSeconds": 180,
      "percentOfPlayersForANewServiceByInstance": 50,
      "forAnewInstanceDelayTimeInSeconds": 300,
      "minNonFullServices": 1,
      "templateInstaller": "INSTALL_ALL",
      "maxServiceCount": -1
    },
    "requiredPermission": null
  }
}
```

Can be somehow mitigated by setting the "minServiceCount" higher so it won't stop the servers when there are only 1-2 left. But the issue still happens when a set of servers is full and one service is completely empty. The empty server is restarting every 2-3 minutes even if no players leave/join the server.

**Comment by derklaro** [comment]
The report module got rewritten for the next release and your issue should be fixed. Thanks for your report!
