### ISSUE TITLE
cloudnet funktioniert nicht.

### ISSUE THREAD

**Issue by LOGOXX123** [CloudNetService/CloudNet-v3#464]
Hallo also ich  habe cloudnet installiert und wollte in putty cloudnet einrichten ich musste eine ip hinzufügen da war eine standart ip die richtig war aber habe troztzdem versucht die von meinem server aber ging nicht dann wusste ich nicht die standart ip und man konnte nicht zurück gehen dann dachte ich mir ich lösche cloudnet und lade es von neu herunter ich geh putty immer noch ip hinzufügen habe dann die erste die mit der pfeil taste kam hinzugefügt und als ich fertig war kammen nur noch error weil der order eigentlich cloudnet hieß da ich es von neu installiert hatte habe ich es cloud gennant dann habe ich cloud order gelöscht und denn in cloudnet gemacht trotzdem ging es nicht und habe dann putty geschlossen und wieder rein cd /home/cloudnet/ ./start.sh ich komme wieder dort rein wo nix funktioniert ich kann clear schreiben passiert nix ich kann alles schreiben passiert nix danach habe ich cloudnet wieder gelöscht und so gelassen nächster tag war trotzdem immer noch dieses wenn ich ./start.sh mache ich wieder dort hin komme wo kein befehl geht nicht mal help das wird einfach da hin geschrieben. Ich beschäftige mich schon etwas länger sogar damit weil ich da da da davor cloud hatte alles ging wollte motd ändern habs gemacht ging der server nicht mehr an wieder cloudnet von neu ändere bild ging der server net mehr aber da gebe zu das war meine schuld 1600 x 900 bild xD dann ging der server net mehr dann wieder gelöcht weil ich das cloudbild nicht mehr hatte..... und ich hoffe ihr könnt mir dabei helfen ich habe meinen server vor 1 monat bestellt und 10verbleibende tage und er funtkioniert immer noch net xD

![screen](https://user-images.githubusercontent.com/83647839/117004895-e935ba00-ace6-11eb-925e-e077657358f9.png)

**Comment by Sarsum** [comment]
Moin,

deinen Text habe ich leider nicht wirklich verstanden.
Aus dem Screenshot lässt sich aber schließen, dass da wohl ein Fehler aufgetreten ist.
Bitte schau einmal in die Log Dateien und schick uns den Fehler dann.

**Comment by LOGOXX123** [comment]
Wo sehe ich sie denn, weil ich habe nur dev, extras, launcher, start.

**Comment by Sarsum** [comment]
Im Installationsverzeichnis unter local/logs/ sollte ein genereller und ein Error Log sein.

**Comment by LOGOXX123** [comment]
Das gibst   leider nicht wenn sie wollen ich schicke screen sogar ich habe in allen verzeichnessin geguckt. Wie gesagt es ist nur dev extras launcher start.sh drauf und in dennen gibst auch kein local und logs.

**Comment by LOGOXX123** [comment]
Ich könnte mal ihnen die daten vom server geben über discord wenn nix anderes geht.
Dann könnten sie sich mal einloggen über winscp oder so und putty

**Comment by Sarsum** [comment]
> Ich könnte mal ihnen die daten vom server geben über discord wenn nix anderes geht.

Fernwartung bieten wir nicht an ;)

Starte die Cloud Mal bitte mit `java -jar launcher.jar`, dann wird die Cloud nicht in einem Screen gestartet und du kannst uns die ganze Ausgabe schicken.

**Comment by LOGOXX123** [comment]
Ok also ich starte es mit launcher.jar also doppel klick halt und was meinen sie mit ausgabe? wieder dann eins screenshot?

**Comment by Sarsum** [comment]
Ne, starte die Cloud bitte über die Befehlszeile mit dem Befehl den ich dir geschickt habe. Danach scrollst du bitte so weit es geht nach oben und kopierst den gesamten Log.

**Comment by Sarsum** [comment]
Alternativ kannst du auch gerne auf unseren Support Discord https://discord.cloudnetservice.eu joinen, das macht die Kommunikation eventuell etwas angenehmer als per GitHub Issue.

**Comment by LOGOXX123** [comment]
wenn ich es verstanden habe also cd /home/clodunet/ dann java -jar oder launcher.jar dann ganz oben dann kopiere ich denn log aber ich weiss nicht so wie man in Putty kopiert xd tut mir leid wissen sie es? sonst schaue ich es bei google

**Comment by LOGOXX123** [comment]
ich war mal drauf aber da gabs kein support ich war heute mal drauf xD aber gabs kein support lass uns lieber erstmal über discord oder willst du unbedingt  dann kein problem?

**Comment by Sarsum** [comment]
> ich war mal drauf aber da gabs kein support ich war heute mal drauf xD aber gabs kein support lass uns lieber erstmal über discord oder willst du unbedingt dann kein problem?

Naja, man sieht die Support Channel erst wenn man die Regeln akzeptiert hat.

**Comment by LOGOXX123** [comment]
oh ehhhhhhhh

**Comment by Sarsum** [comment]
> wenn ich es verstanden habe also cd /home/clodunet/ dann java -jar oder launcher.jar dann ganz oben dann kopiere ich denn log aber ich weiss nicht so wie man in Putty kopiert xd tut mir leid wissen sie es? sonst schaue ich es bei google

Du musst den Text in PuTTY nur markieren und dann wird er automatisch kopiert.

**Comment by LOGOXX123** [comment]
okay also stimmt das was ich meinte cd......

**Comment by LOGOXX123** [comment]
dann java -jar.....

**Comment by LOGOXX123** [comment]
ja? xD ich brauch dafür ne antwort sonst habe ich angst das es falsch ist

**Comment by Sarsum** [comment]
Du musst das halt im Installationsverzeichnis der Cloud ausführen. Aber die grundlegende Administration eines Linux Server können wir dir beim besten Willen trotzdem nicht beibringen.

**Comment by LOGOXX123** [comment]
aaaaaa dachte putty kkk ich weiß es

**Comment by LOGOXX123** [comment]
ja eif launcher rein da dann kopierne

**Comment by LOGOXX123** [comment]
xdddd

**Comment by LOGOXX123** [comment]
ladet.

**Comment by LOGOXX123** [comment]
okay du meinst ganz oben

**Comment by Sarsum** [comment]
Ich meine damit, dass wir den gesamten Output der Cloud brauchen.

**Comment by LOGOXX123** [comment]
das sind nur zeichen und so

**Comment by LOGOXX123** [comment]
PK
   "‰°P           	   META-INF/ PK
   "‰°P_£
FŠ   ·      META-INF/MANIFEST.MF}Ì±
ƒ0@Ñ=ðò0MµêV$CA;Tèž¾<i F1qèß×B¡[×Ëáö&¸‘bwZ£›C“IÈ9ë¢õ&Æ&³ö•v‡€~Þl ÞlŸ´Bû)WJÝ7pv™O…dÒþû}(ÈÅMwú<hQ$ªr6,„ntøWË¢ªË£<©RU5gœ½PK
   íˆ°P              de/ PK
   íˆ°P              de/dytanic/ PK
   íˆ°P              de/dytanic/cloudnet/ PK
   íˆ°P              de/dytanic/cloudnet/launcher/ PK
   íˆ°P           %   de/dytanic/cloudnet/launcher/version/ PK
   íˆ°P           ,   de/dytanic/cloudnet/launcher/version/update/ PK
   íˆ°Pú¤
t  V  C   de/dytanic/cloudnet/launcher/version/update/RepositoryUpdater.class¥Wëå~fwvg³nIˆDiDÜÝ$¬‚ŒH1 a
4	7Aíd÷5˜ìLggÐ‹
µ–Ú‹µ­-jiÅVhV­Y£þÔo~èÔ/ÒçÙ[6“J~y/gÎ9ï9ÏsÞ33ÿþê“ÏÜ‹“À‰N&ñ<¡áÉ$TœÃSrø^úaÈa2|
O'¡KS	LËÙLà”œOKMK3	°¥ÐIâûp¥°”äàµ#‡²ÜžIâ Îj8—D/f5œOb~ á‡Iü?ÖðŒœŸ•êÏÉÕ….jøIžÇOåþ
?ÓpIÃÏDË®¥ #wÊ8cd-£8•÷\³8õ‚5®pì’éÙîìá–L»¨ i8N}³zÊô-OŽÕÕ(r…%Œ’˜0gDÉ3fÊˆ‚UžáN	ïÓù@±+8±hÚÙ§MKdÞ4ÏŒï4‹¦·KÁÚÔÒÒG¨CvAÐaÎ,ŠÑòÌ¤p'ŒIKÈì¼a1\Sî«BÕ›6K
¾+ˆlaÖ3Šf>›·ìr¡(<º.óÓÂÍž	Ê–‚á‰l#ŸÃ¾Àe\+Æ=#ú1Ãñkx‘¾e¤
Ò©°LB‚œè9®í×3ƒêtÊžieÕå<«Ý,:efÂ˜!½ïoˆ©Õ&Îå…ãùD¬m:n¸&¦ÎêjfM¸KÎ¦›9Óð
¿ôO%a–µ×”À¥CàËSf¥‰µC‰%ÏcK§+•­1j•]W½ºj'eû–TV§ï·µ¸¢©4Ë«ƒÏ&Z+¬»vbk%Çí²›A¢ÝKØÞ*tìÀ¯X»Y¿ÆK
ni}OÙ´
ÂÕñ¼¬ã·Ó‘ÅÝ:¶ãnžà6Áû;¿Ç+D ŒnÀ	>¯Õ@•,—ñ*sjøh<y das ist sowas

**Comment by LOGOXX123** [comment]
erklär das mal in einem satz mein verzeichnes heißt cloudnet und drinne finde ich launcher.jar du hast gesagt ich soll es ausführen?

**Comment by LOGOXX123** [comment]
soll ich java -jar hinzufügen oder was meinst du?

**Comment by Sarsum** [comment]
Du musst einfach nur den Befehl `java -jar launcher.jar` ausführen

**Comment by LOGOXX123** [comment]
du meinst ich soll java -jar und launcher.jar ausführen also befehl ich soll es also in cloudnet ausfürhen also neuen ordner oder puTTy

**Comment by Sarsum** [comment]
Nein. Das ist alles ein zusammenhängender Befehl, du musst ihn nur so kopieren wie ich ihn geschickt habe und im Installationsverzeichnis einfügen. Ohne dabei `./` oder sonstiges hinzuzufügen

**Comment by LOGOXX123** [comment]
installationsverzeichnis also das cloudnet verzeichnis wir reden hier nicht über PuTTy nh?

**Comment by LOGOXX123** [comment]
mir ist nicht so klar wo ich das einfügen soll ja in cloudnet aber in Putty oder wie z.b fillerzills oder winscp sonst habe ich es verstanden

**Comment by Sarsum** [comment]
Wir reden über beides. Du musst den Befehl in PuTTY ausführen während du dich gerade im Installationsverzeichnis befindest

**Comment by LOGOXX123** [comment]
teoritisch kann man es in beiden machen

**Comment by LOGOXX123** [comment]
Okay mache ich jetzt sofort

**Comment by LOGOXX123** [comment]
Ok habs :D ich habe es irgendwie ganze zeit gewussst im ersnst aber ich tue nix wenn ich net weiß ob es richtig ist und weil du es ganze zeit installationsverzeichnis genannt hast dachte ich irgendwie an winscp und oben hattest du gesagt kein putty xD

**Comment by LOGOXX123** [comment]
brauch ich einen cluster?

**Comment by Sarsum** [comment]
Nein, ich denke nicht

**Comment by LOGOXX123** [comment]
Ok bei der ip kann ich es standart lassen also was da steht

**Comment by LOGOXX123** [comment]
ich meine host and port

**Comment by LOGOXX123** [comment]
und wenn man mehr pixel beim server icon hat funtkioniert automatisch cloudnet nicht mehr?

**Comment by Sarsum** [comment]
Normalerweise kannst du IP und Port so lassen, ja.

Und das Server-Icon muss generell 64x64 Pixel groß und im PNG Format sein.

**Comment by LOGOXX123** [comment]
kk :D

**Comment by LOGOXX123** [comment]
über uns habe ich dich genervt? wenn ja tut mir leid

**Comment by LOGOXX123** [comment]
xD diese frage war etwas unhoflfich glaub ich

**Comment by Sarsum** [comment]
Wenn die Cloud jetzt läuft, kannst du Mal `shutdown` eingeben (und das anschließend bestätigen) und die Cloud danach versuchen sie wieder normal mit der start.sh starten

**Comment by LOGOXX123** [comment]
sarsum es tut mir so leid hatte kurz kein internet mehbr

**Comment by LOGOXX123** [comment]
jo mach ich

**Comment by LOGOXX123** [comment]
wo ist die eula.txt weil der server startet nicht wenn ich net da rein gehe,.....

**Comment by LOGOXX123** [comment]
obwohl ich die eula yes gemacht habe

**Comment by LOGOXX123** [comment]
ich bin von putty geflogen soll ich wieder diesen befehl oder einfach ./start.sh aber konnte noch kein shutdown

**Comment by Sarsum** [comment]
Starte am besten deinen Server neu. Das ist einfacher als die Cloud über htop zu stoppen.

**Comment by LOGOXX123** [comment]
kk

**Comment by LOGOXX123** [comment]
ich kann mich trotzdem nicht verbinden mit dem server

**Comment by LOGOXX123** [comment]
in Putty bevor mein internet weg war stand ich soll in eula.txt rein damit der server startet sonst startet er nicht

**Comment by Sarsum** [comment]
Die Cloud fragt dich beim ersten Setup ob du die Eula akzeptierst. Sofern du das getan hast, musst du dich darum nicht mehr kümmern.

**Comment by LOGOXX123** [comment]
okay hab ich getan aber der server geht immer noch nicht

**Comment by Sarsum** [comment]
Dann schick uns Mal bitte zuerst die Ausgabe von `ser list`

**Comment by LOGOXX123** [comment]
OH NO xD man AAA ich hab ja noch net nen proxy erstellt ich dummi

**Comment by LOGOXX123** [comment]
im sorry

**Comment by LOGOXX123** [comment]
ich kann jtz eif ./start.sh? und mein proxy lobby erstelen?

**Comment by Sarsum** [comment]
Wie gesagt, probier das Starten mit der start.sh bitte aus (ob das funktioniert).
Bitte beachte, dass du die Konsole dann wie bei Screen üblich mit Strg+A+D verlassen musst.

**Comment by LOGOXX123** [comment]
warum mit strg a d habe es immer einfach geschlossen?

**Comment by LOGOXX123** [comment]
meine tastartur hat nur ctrl alt und kein strg

**Comment by LOGOXX123** [comment]
das starten funktioniert

**Comment by Sarsum** [comment]
> warum mit strg a d habe es immer einfach geschlossen?

Mit Strg+A+D läuft die Cloud im Hintergrund weiter und du kannst auch nachdem die PuTTY Verbindung geschlossen wurde noch wieder auf die Konsole von CloudNet zugreifen

> meine tastartur hat nur ctrl alt und kein strg

Ctrl ist das gleiche wie Strg

> das starten funktioniert

Super! Hast du ansonsten noch Fragen?

**Comment by LOGOXX123** [comment]
ja klar

**Comment by LOGOXX123** [comment]
proxy lieber bungeecord nh?

**Comment by LOGOXX123** [comment]
ich habe noch einige fragen

**Comment by LOGOXX123** [comment]
soll ich die lobby MINECRAFT_SERVER machen oder bungeecord?

**Comment by Sarsum** [comment]
> proxy lieber bungeecord nh?

Das musst du selber wissen was für deinen Anwendungsfall am besten passt, aber Bungeecord ist sicherlich eine der einfacheren Methoden.

> soll ich die lobby MINECRAFT_SERVER machen oder bungeecord?

MINECRAFT_SERVER, die Lobby ist dann ja ein Minecraft Server und kein Bungeecord

**Comment by LOGOXX123** [comment]
KK

**Comment by LOGOXX123** [comment]
ich kann mich immer noch nicht verbinden habe jetzt lobby proxy1 und habe denn proxy 1 gestartet wir haben eigentlich eine domain abert damit erreiche es nicht ich versuche es mal mit der nromalen ip

**Comment by LOGOXX123** [comment]
ist auch mit der normalen ip nicht online

**Comment by Sarsum** [comment]
Dann schick uns bitte mal die Ausgabe von `ser list`

**Comment by LOGOXX123** [comment]
screenshot?

**Comment by LOGOXX123** [comment]
9783afc0 | Name: proxy-1 | Node: Node-1 | Status: RUNNING | Address: 127.0.1.1:25565 | Connected | Players: 0/0
[04.05 19:34:34.482] COMMAND: => Showing 1 service(s); Online: 1; Ingame: 0

**Comment by Sarsum** [comment]
Kopiert und im Codeblock wäre noch schöner, aber Screenshot geht auch

**Comment by LOGOXX123** [comment]
hab

**Comment by Sarsum** [comment]
Naja, du hast in der config.json die lokale IP 127.0.0.1 stehen. Ersetz die mal bitte mit der externen IP deines Servers.

P.S.: Bitte pack Konsolen Ausgaben immer in Codeblöcke, die kannst du so
\`\`\`
Inhalt
\`\`\`
machen

**Comment by LOGOXX123** [comment]
wie mache ich das denn codeblöcke

**Comment by LOGOXX123** [comment]
bei port einfach so lassen?

**Comment by Sarsum** [comment]
> wie mache ich das denn codeblöcke

Dafür habe ich dir doch extra ein Beispiel geschickt, das kannst du einfach kopieren und dann den Inhalt ersetzen.

> bei port einfach so lassen?

Ja

**Comment by LOGOXX123** [comment]
soll ich überall wo host steht meine ip schreiben es steht 3mal host verteilt

**Comment by Sarsum** [comment]
Ja, das musst du überall ändern.

**Comment by LOGOXX123** [comment]
warum ist closed

**Comment by LOGOXX123** [comment]
noooooooooooo sarsummmmmmmm

**Comment by Sarsum** [comment]
Du hast das Issue selber geschlossen, ich habe mich schon gewundert ob das richtig ist und hab es jetzt mal wieder geöffnet.

**Comment by LOGOXX123** [comment]
das war ausversehen :(

**Comment by LOGOXX123** [comment]
soll ich unter  whitelist auch ip ändern?

**Comment by Sarsum** [comment]
Unter IP Whitelist muss die IP deines Servers auch stehen, damit sich die Unterserver zur Cloud verbinden können.

**Comment by LOGOXX123** [comment]
ich habe jetzt überall meine ip ich habe cloudnet reloaded geht immer noch nicht

**Comment by Sarsum** [comment]
Starte die Cloud am besten einmal neu und schick mir dann wieder die Ausgabe von `ser list`

**Comment by LOGOXX123** [comment]
neu starten wie meinst du das meinst du server restarten?

**Comment by LOGOXX123** [comment]
weil cloud kann man net neu starten oder XD

**Comment by Sarsum** [comment]
> neu starten wie meinst du das meinst du server restarten?

Nein, ich sage schon was ich meine.

> weil cloud kann man net neu starten oder XD

Doch, du kannst sie mit `shutdown` stoppen (wie du es schonmal gemacht hast) und danach wieder Starten.

**Comment by LOGOXX123** [comment]
XXDDDDD kk bro

**Comment by LOGOXX123** [comment]
bei service list ist aufeinmal nix mehr

**Comment by LOGOXX123** [comment]
und ich kann mich immer noch net verbinden

**Comment by Sarsum** [comment]
> und ich kann mich immer noch net verbinden

Das ist kein Wunder wenn bei Service List nichts drin ist.

> bei service list ist aufeinmal nix mehr

Hast du Tasks die automatisch Starten sollen? Ist bei denen der MinServiceCount auf 1 gesetzt?

**Comment by LOGOXX123** [comment]
minservicecount 0

**Comment by LOGOXX123** [comment]
lobby

**Comment by LOGOXX123** [comment]
proxy auch 0

**Comment by Sarsum** [comment]
Dann setz das doch mal beides auf 1 mit diesem Befehl https://cloudnetservice.eu/docs/3.3/commands/tasks/#tasks-task-set-minservicecount
Dann starten die auch automatisch.

**Comment by LOGOXX123** [comment]
ok ich hab beides auf 1

**Comment by Sarsum** [comment]
Dann sollten die Services automatisch starten

**Comment by LOGOXX123** [comment]
ja hab auch aus gemacht das die bei stop gelöscht werden sollen

**Comment by LOGOXX123** [comment]
endlich

**Comment by LOGOXX123** [comment]
20tage nur das thema cloudnet

**Comment by LOGOXX123** [comment]
UND jtz geht es endlich

**Comment by Sarsum** [comment]
Gibts gerade sonst noch etwas deinerseits?

**Comment by LOGOXX123** [comment]
maxheapmemory macht wieviel die Lobby benutzten darf nh?

**Comment by LOGOXX123** [comment]
ja :D

**Comment by Sarsum** [comment]
> maxheapmemory macht wieviel die Lobby benutzten darf nh?

Ja, genau. Das ist der RAM in MB den jede Lobby bekommt.

**Comment by LOGOXX123** [comment]
und proxy? hat das auch aber dann für was ist dann der ram für cloudnet

**Comment by LOGOXX123** [comment]
bei cloudnet config  da kann man ja auch memory wenn das 4000 ist und man lobby 8000 hat was ist dann? oder kann dann die lobby nur 4000?

**Comment by LOGOXX123** [comment]
für was sind die proxies beim server?

**Comment by LOGOXX123** [comment]
wie tue ich eine lobby map in die lobby?

**Comment by Sarsum** [comment]
> und proxy? hat das auch aber dann für was ist dann der ram für cloudnet

Für den Proxy kannst du genauso (in der Proxy Task) den RAM pro Proxy Instanz setzen. Den Ram für die Cloud (wie viel die Services verwenden dürfen) kannst du in der config limitieren.

> bei cloudnet config da kann man ja auch memory wenn das 4000 ist und man lobby 8000 hat was ist dann? oder kann dann die lobby nur 4000?

Das in der Config ist das generelle Maximum für alle Services. Wenn das auf 4000 steht und die Lobby 8000 hat, wird die Lobby nicht starten weil nicht genug Ram frei bzw. erlaubt ist.

> für was sind die proxies beim server?

Die Frage verstehe ich nicht, könntest du die nochmal anders formulieren?

> wie tue ich eine lobby map in die lobby?

Indem du sie ins Template bzw. den statischen Ordner der Lobby packst.

**Comment by LOGOXX123** [comment]
wenn ich dann noch einen proxy habe was macht er dann

**Comment by Sarsum** [comment]
> wenn ich dann noch einen proxy habe was macht er dann

Zur Lastenverteilung dienen

**Comment by LOGOXX123** [comment]
was meinst du damit heißt das wenn der proxy1 server überlasstet ist dient der 2 als fallback?

**Comment by LOGOXX123** [comment]
wenn ich in proxy plugins rein tuhe sind die dann immer da auch wenn man zur lobby geht oder citybuild?

**Comment by Sarsum** [comment]
> was meinst du damit heißt das wenn der proxy1 server überlasstet ist dient der 2 als fallback?

Nein, die Spieler müssen sich schon explizit zum zweiten Proxy verbunden haben

> wenn ich in proxy plugins rein tuhe sind die dann immer da auch wenn man zur lobby geht oder citybuild?

Nein, Proxy Plugins sind keine Spigot Plugins.

**Comment by LOGOXX123** [comment]
also wenn man im server ist und proxy 2 verbindet was ist dann xD also ehhhhhhhhhh

**Comment by LOGOXX123** [comment]
checke es net so

**Comment by Sarsum** [comment]
Also, der Proxy 1 läuft auf dem Standard Port 25565. Du kannst dich dann auf deinen Server verbinden ohne einen Port anzugeben und landest auf Proxy 1 oder du gibst den nächsten Port an und landest auf Proxy 2

**Comment by LOGOXX123** [comment]
wenn man bw haben will und es beim schild macht wenn es startet dann kann man ja nochmal verbinden für eine freihe bw lobby braucht man dann eine lobby2

**Comment by LOGOXX123** [comment]
okay

**Comment by LOGOXX123** [comment]
halt wenn die bw runde startet und dann wird ja ne neue bw runde gestartet braucht man dafür einen bw-2?

**Comment by LOGOXX123** [comment]
nein oder?

**Comment by Sarsum** [comment]
> wenn man bw haben will und es beim schild macht wenn es startet dann kann man ja nochmal verbinden für eine freihe bw lobby braucht man dann eine lobby2

Wie dein Bedwars Plugin funktioniert kann ich dir leider nicht beantworten. Viele laufen aber so, dass sich die BW Lobby einfach auf dem selben BW Server wie die BW Map befindet.

> halt wenn die bw runde startet und dann wird ja ne neue bw runde gestartet braucht man dafür einen bw-2?

Wenn man die Cloud gut aufgesetzt hat, sollten die BW Server dynamisch sein und ein Template haben. Dann kann die Cloud einfach nach Bedarf mehr BW Server starten und stoppen

**Comment by LOGOXX123** [comment]
ja so will ich das das neue bw server dann starten wenn gerade eine schon läuft

**Comment by Sarsum** [comment]
Dafür kannst du die Smart Config der Tasks verwenden: https://cloudnetservice.eu/docs/3.3/modules/smart

**Comment by LOGOXX123** [comment]
damit das funkti9oniert muss ich das machen waas bei smart module ist nh?

**Comment by LOGOXX123** [comment]
einfach alles

**Comment by LOGOXX123** [comment]
k ik

**Comment by LOGOXX123** [comment]
starte wieder mal xD

**Comment by LOGOXX123** [comment]
ich hab ja noch kein bw server denn erstelle ich über task wie Lobby nh?

**Comment by Sarsum** [comment]
Ja genau, dafür brauchst du eine eigene Task

**Comment by LOGOXX123** [comment]
wie tue ich denn meine lobby map auf die lobby task?

**Comment by Sarsum** [comment]
> wie tue ich denn meine lobby map auf die lobby task?

Du musst sie ins Template packen. Das ist unter `local/templates/Lobby/default/`

**Comment by LOGOXX123** [comment]
einfach die map da rein?

**Comment by LOGOXX123** [comment]
ok habss

**Comment by Sarsum** [comment]
Ja, nenn sie am besten `world`, damit sie direkt geladen wird.

**Comment by LOGOXX123** [comment]
kann ich mit ´tasks task Lobby restart´die lobby restarten?

**Comment by Sarsum** [comment]
Nein, nutz am besten `ser Lobby-1 stop`

**Comment by LOGOXX123** [comment]
und dann wieder start

**Comment by Sarsum** [comment]
Sollte er eigentlich automatisch machen, durch den minServiceCount

**Comment by LOGOXX123** [comment]
muss ich wieder ./start.sh weil habe das gemacht mit strg d a

**Comment by LOGOXX123** [comment]
jtz bin ich im ordner cloudnet

**Comment by Sarsum** [comment]
> muss ich wieder ./start.sh weil habe das gemacht mit strg d a

Nein, musst du nicht. Das startet die gesamte Cloud

**Comment by LOGOXX123** [comment]
wie komme ich dann wieder in die cloud mit screen -x?

**Comment by Sarsum** [comment]
Ja, genau

**Comment by LOGOXX123** [comment]
kk my friend

**Comment by LOGOXX123** [comment]
/spawn und /spawnset und /hub ist dabei?

**Comment by Sarsum** [comment]
> /spawn und /spawnset und /hub ist dabei?

/hub ist durch die Bridge dabei. /spawn oder so aber nicht.

**Comment by LOGOXX123** [comment]
kennst du nen plugin mit spawn? weil essentials soll nicht in die lobby

**Comment by Sarsum** [comment]
Das hat nichts mit der Cloud zutun, tut mir leid.

**Comment by LOGOXX123** [comment]
oder nah hub geht auch

**Comment by LOGOXX123** [comment]
du hilfst mir nur mit der cloud nh?

**Comment by LOGOXX123** [comment]
wie kann ich hub setzten?

**Comment by Sarsum** [comment]
> oder nah hub geht auch

Ja, das ist ein CloudNet Befehl.

> du hilfst mir nur mit der cloud nh?

Genau

> wie kann ich hub setzten?

Das sendet dich auf einen zufälligen Fallback Server

**Comment by LOGOXX123** [comment]
nein wie setzte ich das das ma wenn man /hub macht an einem bestimmten ort spawnt

**Comment by Sarsum** [comment]
Das geht nicht, dafür brauchst du ein Lobby Plugin.

**Comment by LOGOXX123** [comment]
achso ja

**Comment by LOGOXX123** [comment]
darfst du mir kein lobby plugin empfehlen?

**Comment by Sarsum** [comment]
Das ist kein Thema für den CloudNet Support, deswegen empfehle ich auch nichts.

**Comment by LOGOXX123** [comment]
was macht placeholderapi das frage ich mich schon immer

**Comment by Sarsum** [comment]
Das ist kein Thema für den CloudNet Support.

**Comment by LOGOXX123** [comment]
ich hatte noch cloudnet fragen

**Comment by Sarsum** [comment]
Bitte wende dich für weitere Fragen an den Support auf unserem Discord Server: https://discord.cloudnetservice.eu
Wir schließen hiermit dann das Issue.
