### ISSUE TITLE
cloudperms geht nicht

### ISSUE THREAD

**Issue by LOGOXX123** [CloudNetService/CloudNet-v3#465]
Hallo, cloudperms geht nicht, obwohl ich es aktiviert habe

wenn man beim cloudnet discord ist was muss man tuen um support zu kriegen?
Denn es gibst kein #support

**Comment by Sarsum** [comment]
Moin, auf die meisten Kanäle hat man erst Zugriff nachdem man die Regeln akzeptiert hat.
