### ISSUE TITLE
cloudperms funktioniert nicht obwohl ich es angeschaltet habe.

### ISSUE THREAD

**Issue by LOGOXX123** [CloudNetService/CloudNet-v3#466]
cloudperms funtkioniert nicht obwohl ich es an habe und der Befehl geht auch nicht mehr wenn ich über Konsole mache steht da succesful aber trotzdem habe ich dann denn rang nicht

**Comment by Liam024** [comment]
Did you mean "CloudPerms doesn't work" instead of "works" in the title? It's best to write in English next time, then more will understand it.

**Comment by LOGOXX123** [comment]
cloudperms doesnt work although i have it true

**Comment by LOGOXX123** [comment]
LOL i had cloudperms work XDD bruh
