### ISSUE TITLE
cloudperms prefixes werden nicht  angezeigt.

### ISSUE THREAD

**Issue by LOGOXX123** [CloudNetService/CloudNet-v3#472]
Wenn ich cloudnet ausschalte und wieder anschalte resetet cloudnet meine Lobby welt.

**Comment by fadeoffical** [comment]
Das ist kein Bug, sondern ein feature. Damit die lobby immer erhalten bleibt musst du entweder das template updaten oder den service static machen. Genaueres kann ich dir leider nicht sagen.

**Comment by LOGOXX123** [comment]
Fade es tut mir leid das ich jedes malö es neu geöffnet habe das wird nicht wieder passieren ich habe halt 1monat aus dem server nix machen können weil es ständig probleme mit cloudnet gabs :( wenn du willst lösche ich alles

**Comment by fadeoffical** [comment]
naja ich bin hier kein moderator oder sonstiges. Ich bin auch nur user ^^

**Comment by LOGOXX123** [comment]
weiß ich schon

**Comment by LOGOXX123** [comment]
du meintest screenshot also das kann man eigentlich nicht machen weil wenn du denn befehl eingibst passiert es ja schon wie soll man dann ein scrennshot mache xd da kommt halt wenn man /cloudperms....             please use the command help

**Comment by LOGOXX123** [comment]
was meinst du mit zwietrich

**Comment by fadeoffical** [comment]
Zeig mal den genauen command, den du eingibst.
Außerdem, was meinst du mit "zwietrich"?

**Comment by LOGOXX123** [comment]
das meintest du und ich danke dir 1000mal das du mir hiflst

**Comment by LOGOXX123** [comment]
mit dem readme

**Comment by LOGOXX123** [comment]
ich schicke dir jtz nen screen

**Comment by LOGOXX123** [comment]
nur noch kurz

**Comment by fadeoffical** [comment]
1) Sehr gerne helfe ich dir mit deinem Problem.
2) Das mit der README.md war folgendermaßen gemeint: Ich hatte (weswegen auch immer) in Erinnerung, dass wenn man auf den Banner clickt, dass man auf den Discord geleitet wird. Dies stimmt so nicht. Stattdessen steht dort die URL zum Discord Server/Guild
3) Der Screenshot würde weiterhelfen, danke

(Nur so am Rande: Die Kommentar-Funktion ist mehr für sachliche (Kurz-) Texte als für kleine Ein-Satz Nachrichten.
Es ist unglaublich schwer jemandem zu folgen wenn viele kurze Nachrichten da sind)

**Comment by LOGOXX123** [comment]
kannst du mir die screenshot tastenkombination sagen für laptop ich suche sie die ganze zeit aber keine funtkioniert ich konnte sie aber habe sie vergessen

**Comment by fadeoffical** [comment]
Zu wissen, wie man ein Screenshot aufnimmt, liegt eher in deiner Verantwortung.
Jedoch sollte es (unter Windows) ein Programm namens "Snipping Tool" geben; damit kannst du es mal versuchen.

**Comment by LOGOXX123** [comment]
kann es daran liegen weil ich gerade mit labymod bin?

**Comment by fadeoffical** [comment]
Das kann ich dir leider nicht beantworten.
Was mir jedoch gerade aufgefallen ist, ist, dass wir glaube ich im falschen Issue sind. Wenn du dich auf das issue mit cperms beziehst, sollten wir zum anderen Issue wechseln

**Comment by LOGOXX123** [comment]
kenne die tastenkombinatrion jetzt geht trotzdem nicht soll ich normales mc?

**Comment by LOGOXX123** [comment]
wie beziehe ich mich da drauf?

**Comment by LOGOXX123** [comment]
normales mc hat geklappt.

**Comment by fadeoffical** [comment]
1) Das Windows Snipping Tool ist nicht an Minecraft gebunden
2) Die Geschichte mit dem Screenshot wurde in [deinem anderen issue](https://github.com/CloudNetService/CloudNet-v3/issues/471) angesprochen.
3) Github issues sind immer noch kein Chat. Wenn du den Screenshot hast, schicke ihn hier bitte rein, danke

**Comment by LOGOXX123** [comment]
Screenshot

https://user-images.githubusercontent.com/83647839/117504927-7e54df00-af83-11eb-8f93-95f7ee047b99.png)

danach kommt please use the command help.

wenn ich über die konsole denn befehl ausführe steht: succesfull aber habe denn rang nicht bekommen

**Comment by fadeoffical** [comment]
der cmd is `/cloud perms ...`

**Comment by LOGOXX123** [comment]
was meinst du? damit hat es früher immer funktioniert ich weiß nicht was du meinst cmd ist die windows konsole


irgendwie hast du recht

erklär das mal

über konsole ist der befehl nur perms

**Comment by LOGOXX123** [comment]
schau dir das mal an

https://user-images.githubusercontent.com/83647839/117506135-62ead380-af85-11eb-847c-80405f22e227.png)


nah das ist nur die software.................

**Comment by DSeeLP** [comment]
Du führst mit perms in der console den cloudperms command aus. Jedoch in Minecraft führst du mit /perms den permissions Command von BungeeCord aus. Du kannst mit /cloud <befehl aus der konsole> eigentlich jeden befehl ausführen. Man muss in Minecraft /cloud perms nutzen.

**Comment by LOGOXX123** [comment]
DSeeLP wenn ich über console mir rang gebe bekomme ich denn nicht

**Comment by LOGOXX123** [comment]
der befehl ist so jedoch bekomme ich denn rang nicht

ich kann dir morgen screenshots schicken jtz bin ich mal off bye
