### ISSUE TITLE
WaterdogPE error

### ISSUE THREAD

**Issue by xxFLORII** [CloudNetService/CloudNet-v3#475]
**Description of the bug:**

1. Download CloudNET WaterdogPE branch
2. Create a proxy with WaterdogPE
3. See the error

**Expected behavior:**

**Comment by 0utplay** [comment]
This is just a warning when using Java 9+ and is not related to cloudnet

**Comment by xxFLORII** [comment]
no, that's caused by a cloudnet plugin i think

**Comment by juliarn** [comment]
The WaterdogPE branch is not ready yet. I can look into it and complete it in the next time.

**Comment by juliarn** [comment]
Try this version: https://ci.cloudnetservice.eu/job/CloudNetService/job/CloudNet-v3/job/feature%252Fwaterdogpe-support/lastSuccessfulBuild/artifact/cloudnet-launcher/build/libs/launcher.jar
