### ISSUE TITLE
OnlyProxyJoin rejects connections to the server

### ISSUE THREAD

**Issue by byKeksYT** [CloudNetService/CloudNet-v3#477]
**Description of the bug:**

If I create a proxy and a normal server in the CloudNet setup, the plugon "OnlyProxyJoin" rejects the connections to the main server.

**Steps to reproduce this bug:**

1. Start CloudNet normally with ./start.sh
2. Let CloudNet configure a default proxy with BungeeCord
3. Let CloudNet configure a default lobby server with paperspigot-1.8.8
4. Try to join the server
5. You'll see the error message in the console

**Expected behavior:**

After creating the proxy and the lobby server being able to join it without further problems.

**Screenshots:**

![Bild_2021-05-14_171133](https://user-images.githubusercontent.com/54219222/118291049-6d522380-b4d7-11eb-930a-b1a25d6a1f7f.png)

**Environment and used hardware:**
 
 
 System specifications: CPU: Intel Xeon E5-2680 v2
 OS: Debian 10
 Version: CloudNet version 3.3.0-RELEASE Hurricane

**Comment by derklaro** [comment]
Can you please take a closer look to the warning message?

**Comment by byKeksYT** [comment]
How do you mean it?

**Comment by derklaro** [comment]
Just read it

**Comment by byKeksYT** [comment]
Yes, I read it but how do I change the "remoteAddress" in order that it works?

**Comment by derklaro** [comment]
Change it to a remote address or use the snapshot version which will work with loopback addresses

**Comment by byKeksYT** [comment]
Which snapshot version do you mean?

**Comment by derklaro** [comment]
3.4
