### ISSUE TITLE
[Question?] Set CloudNet Server Join Power

### ISSUE THREAD

**Issue by einGregor** [CloudNetService/CloudNet-v3#480]
Question? Set CloudNet Server Join Power

How do I set up a server join power on CloudNet?
I know how to set this up in the permission system, but how do I tell the server that it should have a join power of 20, for example

**Comment by derklaro** [comment]
What do you mean with "Server Join Power"?

**Comment by 0utplay** [comment]
Hello, CloudNet v3.3 does not provide a joinpower or permission. In 3.4 a join permission was implemented.

**Comment by einGregor** [comment]
how can i get the 3.4 version

**Comment by 0utplay** [comment]
You can get the 3.4 Snapshot by enabling use-snapshots in the launcher.cnl and restart. But keep in mind that this is a snapshot version

**Comment by einGregor** [comment]
I found all cloudnet permissions on this page: https://pastebin.com/sk4SRifn

HERE the permission:
"cloudnet.joinpower. <joinpower from group> - Allows the player to join a server with the respective JoinPower."

so i thought that there should be a join power

**Comment by einGregor** [comment]
ok nice thanks vor the info whit the snapshot feature

**Comment by einGregor** [comment]
if I have the 3.4 version, where do I find the point dan for the server join power and do I have to create the task again or not

**Comment by einGregor** [comment]
@derklaro 

With the Server Join Power I meant:

I would like to make a sub-server name team where only the team members can join and nobody else

**Comment by 0utplay** [comment]
On 3.4 you can set a permission in your taskname.json in /local/tasks

**Comment by einGregor** [comment]
1. How do I see if I have the 3.4 version?

2. Do I have to enter the mannuel or is it already prefabricated and I just have to change the value

**Comment by 0utplay** [comment]
1. Look at the `me` Command
2. Its generated and you can change it to your permission

**Comment by einGregor** [comment]
do I have to reinstall my CloudNet?
Because I changed the "launcher.cnl" on my CludNet and also have the new version.

But when I create a new one under Server, the tasks config is still the same and has not changed

**Comment by 0utplay** [comment]
It's in the properties part of the task config

**Comment by einGregor** [comment]
"deployments": [],
  "properties": {
    "requiredPermission": null,
    "smartConfig": {
      "enabled": false,
      "priority": 10,
      "directTemplatesAndInclusionsSetup": true,
      "preparedServices": 0,
      "dynamicMemoryAllocation": false,
      "dynamicMemoryAllocationRange": 256,
      "percentOfPlayersToCheckShouldAutoStopTheServiceInFuture": 0,
      "autoStopTimeByUnusedServiceInSeconds": 180,
      "percentOfPlayersForANewServiceByInstance": 100,
      "forAnewInstanceDelayTimeInSeconds": 300,
      "minNonFullServices": 0,
      "templateInstaller": "INSTALL_ALL",
      "maxServiceCount": -1
    }
  }
  
  
  This is my Event-Server Task the properties part 
I dont finde it what you mean

**Comment by Sarsum** [comment]
You have to change the `"requiredPermission": null,` to something like `"requiredPermission": "your.join.permission",`

**Comment by einGregor** [comment]
I try it later
Thanks

**Comment by derklaro** [comment]
It looks like you could resolve the issue. If there are still problems, feel free to re-open this issue.
