### ISSUE TITLE
Use Waterfall's methods to add and remove servers

### ISSUE THREAD

**Issue by Sneakometer** [CloudNetService/CloudNet-v3#484]
Related to https://github.com/PaperMC/Waterfall/issues/645
So basically there is a slim chance breaking the TMap in the Configuration class of Waterfall everytime a server is added/removed at the same time another thread is accessing it. Waterfall intruduced a lock object aswell as dedicated addServer() and removeServer() methods to mitigate this issue. I request CloudNet to use these methods, if they are found, or else fall back using the map to still keep the BungeeCord compatibility.

**Reasons for inclusion into the CloudNet code base:**
- Fix synchronization issues accessing the server list
- Possibly fix #482
- Keep BungeeCord compatibility
- Janmm14 suggested this

**Planned audience:**
- All Cloudnet + Waterfall users

**Preview of pseudo code :**
- Check if addServer() and removeServer() methods are present using reflections
- If yes, use them to add and remove Servers in the Bridge Module
- If no, just do it the old way

**Comment by derklaro** [comment]
Implemented in branch `better-service-to-proxy-register` please test and give feedback :) Thank you

**Comment by Sneakometer** [comment]
Now running 1 week in production without any issues. I think it's safe to merge.

**Comment by derklaro** [comment]
Was implemented in 86c49a5a53185b8d432da10fbea9bc30415114b9 and will be available in the next release. Thank you for your report :)
