### ISSUE TITLE
how to create a bungecord on remote host?

### ISSUE THREAD

**Issue by alan67160** [CloudNetService/CloudNet-v3#487]

**Comment by derklaro** [comment]
Can you please describe the issue more detailed?

**Comment by alan67160** [comment]
I hosted a CloudNet on my server and I want to move the bungeecord to a Minecraft hosting, for example, mcprohosting, server.pro

**Comment by alan67160** [comment]
> I hosted a CloudNet on my server and I want to move the bungeecord to a Minecraft hosting, for example, mcprohosting, server.pro

because as you know the Anti-DDoS service is quite expensive therefore moving the bungeecord to their (mcprohosting/serverpro/creeperhost) hosting and use their Anti-DDoS service will be more cheaper

**Comment by derklaro** [comment]
There is no way to get an external proxy into the cloudnet network.
