### ISSUE TITLE
Stop error

### ISSUE THREAD

**Issue by oRIOnTx** [CloudNetService/CloudNet-v3#492]
Hi, i have error when stop cloudnet system. Use latest snapshot.
https://pastebin.com/P5qUUvhm - paste of error
![image](https://user-images.githubusercontent.com/40061096/121804381-cc2dc880-cc4e-11eb-9aab-3d9214d811fd.png)

**Comment by derklaro** [comment]
That's a windows issue, but nothing to be concerned about.
