### ISSUE TITLE
CloudNet-Bridge loads the server very much

### ISSUE THREAD

**Issue by glitchring** [CloudNetService/CloudNet-v3#494]
When you log on to the TPS server, the server can sink to 17

![изображение](https://user-images.githubusercontent.com/73692598/122215475-f03e1380-ceb3-11eb-9a0f-0d4db3731f1b.png)

**Comment by derklaro** [comment]
I just rechecked this behaviour and i can't confirm this... The bridge plugin loads the server a bit (which is not unlikely at all) but not as much as shown in the timings report,,,

**Comment by glitchring** [comment]
And why is everything so bad for me? After each connected player, I have lags and tps jumps, the processor is Ryzen 7 3700X (16 threads), 32 gb

**Comment by derklaro** [comment]
The only thing i can tell you is that a method call by one of your plugins load the server, not the bridge plugin at it's core. Consider the async variant of the method if you really want to call this on the main server thread.

Closing as it is no cloudnet issue in it's core - you can still respond if you need further help.
