### ISSUE TITLE
Snapshot Test result on Windows server 2019

### ISSUE THREAD

**Issue by oRIOnTx** [CloudNetService/CloudNet-v3#509]
Hello everybody! I had the experience of testing cloudnet on Windows server 2019. As a result, I found the following problems:
1. I cannot use my kernels for the server. If I replace the standard kernel downloaded automatically with a new build from paperspigot, then the server shuts down after the start of the launch and enters the cycle.
2. Service management is not working correctly. After the stop or restart command, the service writes that it is prepared and does not start again or does nothing.
3. An error occurred while stopping the system. https://pastebin.com/RK5VKthS

What I used:
1. Windows server 2019
2. CloudNet snapshot 3.4 latest
3. Java 16
4. Paperspigot 1.16.5 & 1.17

**Comment by derklaro** [comment]
Hey, thanks for your time!

> I cannot use my kernels for the server. If I replace the standard kernel downloaded automatically with a new build from paperspigot, then the server shuts down after the start of the launch and enters the cycle.

Are you using the patched version of the paper jar or the paperclip file itself? The paperclip file will lead to that issue.

> Service management is not working correctly. After the stop or restart command, the service writes that it is prepared and does not start again or does nothing.

Just rechecked, looks fine to me...

> An error occurred while stopping the system. https://pastebin.com/RK5VKthS

It's a windows file system issue, there is not much we can do beside of supressing the exception stack trace.

**Comment by oRIOnTx** [comment]
> Hey, thanks for your time!
> 
> > I cannot use my kernels for the server. If I replace the standard kernel downloaded automatically with a new build from paperspigot, then the server shuts down after the start of the launch and enters the cycle.
> 
> Are you using the patched version of the paper jar or the paperclip file itself? The paperclip file will lead to that issue.
> 
> > Service management is not working correctly. After the stop or restart command, the service writes that it is prepared and does not start again or does nothing.
> 
> Just rechecked, looks fine to me...
> 
> > An error occurred while stopping the system. https://pastebin.com/RK5VKthS
> 
> It's a windows file system issue, there is not much we can do beside of supressing the exception stack trace.

Where i can find patched version of paper spigot ? And about second test - it's may possible problem in smartconfig ?

**Comment by derklaro** [comment]
The patched version is located in `caches/patched_version.jar`. Might be a smart config issue but i don't know one...

**Comment by oRIOnTx** [comment]
> Пропатченная версия находится в формате `caches/patched_version.jar`. Может быть проблема с умной конфигурацией, но я ее не знаю ...

![image](https://user-images.githubusercontent.com/40061096/124444744-954b5e00-dd87-11eb-9aa0-7d5c4f15ab80.png)
![image](https://user-images.githubusercontent.com/40061096/124445524-4d790680-dd88-11eb-9d8e-a368165fba56.png)

Ok thanks. When i use service restart - service is stopped and write "is being prepared...". After that, the serverice does not start. If check service list - my service have status "Running", but its false. I same have problem with others services too. I attach  screenshots

**Comment by oRIOnTx** [comment]
I want to solve the problem for myself and also help the community

**Comment by derklaro** [comment]
Can you send the task file?

**Comment by oRIOnTx** [comment]
> Can you send the task file?

https://pastebin.com/27w36VTq
