### ISSUE TITLE
A very critical bug, the server does not restart

### ISSUE THREAD

**Issue by glitchring** [CloudNetService/CloudNet-v3#511]
The server does not start after writing the /restart or /stop command, commands like service Hub-1 restart do not work

**Steps to reproduce the exception:**
1. I started CloudNet myself and waited for all the servers to load
2. I went to the server itself and wrote /stop (/restart) or wrote a command in the terminal service Hub-1 command stop
3. The server did not load and decided to look at the information

**Screenshots:**
![изображение](https://user-images.githubusercontent.com/73692598/124546358-30e5d880-de33-11eb-8408-23e5bb894771.png)
![изображение](https://user-images.githubusercontent.com/73692598/124546525-6e4a6600-de33-11eb-9a51-4574aff109ac.png)
![изображение](https://user-images.githubusercontent.com/73692598/124547025-30017680-de34-11eb-8102-5676f3b47466.png)

Config - https://p.reflex.rip/onix.json

 System specifications: 
 OS: Windows 10
 Version:  3.4.0-SNAPSHOT-fb4128c..
 
 P.S: enabling autoDeleteOnStop doesn't help and staticServices doesn't either

**Comment by oRIOnTx** [comment]
I have a same problem
