### ISSUE TITLE
Failed to apply plugin [id 'org.cadixdev.licenser']

### ISSUE THREAD

**Issue by base2code** [CloudNetService/CloudNet-v3#513]
**Description of the bug:**

Build fails in Docker container

**Steps to reproduce this bug:**
git clone https://github.com/CloudNetService/CloudNet-v3.git
cd CloudNet-v3
docker build -t cloudnetv3 .

**Expected behavior:**

Docker image should build

**Error:**

```FAILURE: Build failed with an exception.

* Where:
Build file '/usr/src/cloudnet-sources/build.gradle' line: 193

* What went wrong:
A problem occurred evaluating root project 'cloudnet-root'.
> Failed to apply plugin [id 'org.cadixdev.licenser']
   > Could not create an instance of type org.cadixdev.gradle.licenser.LicenseExtension.
      > No signature of method: org.gradle.api.internal.model.DefaultObjectFactory.domainObjectContainer() is applicable for argument types: (Class, org.cadixdev.gradle.licenser.LicenseExtension$_closure1) values: [class org.cadixdev.gradle.licenser.LicenseTaskProperties, org.cadixdev.gradle.licenser.LicenseExtension$_closure1@7e41aec9]

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
The command '/bin/sh -c gradle' returned a non-zero code: 1
```

Full log: https://hastebin.com/jikoyoweju.rb

**Environment and used hardware:**

System specifications: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
 OS: Debian 10
 Version: CloudNet 3.3 (latest commit)

**Additional context (optional):**

**Comment by base2code** [comment]
Still not compiling: https://hastebin.com/rolunetodo.sql

**Comment by derklaro** [comment]
Thats now an issue of your configuration, gradle can't resolve `https://repo.maven.apache.org/maven2/`
