### ISSUE TITLE
Making cleaner that there are sub-options

### ISSUE THREAD

**Issue by kubo6472** [CloudNetService/CloudNet-v3#518]
**Description of the new feature:**
Add a character that indicates that the console option in the initial setup includes other options.

**Reasons for inclusion into the CloudNet code base:**
I reinstalled this twice, since I wanted to use paper, but only saw Minecraft_Server in the initial menu.

**Planned audience:**
Newcomers to CN

**Comment by derklaro** [comment]
I see your point but there is not much we can do there - maybe we can clearify that in the installation guide @0utplay ?

**Comment by 0utplay** [comment]
I will have a look at this in the documentation

**Comment by derklaro** [comment]
Closing as this is now a documentation issue, not related to cloudnet directly.

**Comment by kubo6472** [comment]
> Closing as this is now a documentation issue, not related to cloudnet directly.

I meant including it in the initial setup. Not necessarily in the documentation only.
