### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by Rakete2510** [CloudNetService/CloudNet-v3#519]
Könnte man die 1.17 bitte einbinden damit man die clloudnet v3 auch noch weiter nutzen kann

**Comment by juliarn** [comment]
Hey, der 3.4 Snapshot von CloudNet unterstützt die 1.17.X, die 3.3 allerdings noch nicht. Um den 3.4 snapshot zu nutzen, kannst du in der launcher.cnl die Option `use-snapshots` auf true setzen und dann Neustarten.

**Comment by Sarsum** [comment]
Wir arbeiten im Moment am Release der 3.4 Version, diese wird dann auch Unterstützung für 1.17 haben.

Bitte halte dich außerdem beim nächsten Mal an das vorgegebene Issue Template.
