### ISSUE TITLE
wie macht man eine  animated tab und motd?

### ISSUE THREAD

**Issue by NettyByte** [CloudNetService/CloudNet-v3#527]
wie macht man eine  animated tab und motd?

**Comment by 0utplay** [comment]
Animierte MOTDs sind vom Client aus nicht möglich.

Die Header & Footer können durch mehrere Einträge in der config.json des SyncProxy Moduls animiert werden.

Für weiteren Support würde ich dich bitten auf den Discord zu joinen. https://discord.cloudnetservice.eu/

**Comment by NettyByte** [comment]
kann nicht auf den dc joinen und das mit mehre einträge geht nicht

**Comment by derklaro** [comment]
Closing as resolved by support
