### ISSUE TITLE
Man wird vom Server gekickt und nicht auf einen anderen Server verschoben

### ISSUE THREAD

**Issue by Tabeeaaa** [CloudNetService/CloudNet-v3#529]
**Description of the bug:**
Wenn ich einen Service Stoppe dann werde ich vollständig vom Server gekickt mit der default "Server closed" Nachrricht und ich werde nicht mit einem anderen Service verbunden, obwohl einer vorhanden gewesen wäre.

**Steps to reproduce this bug:**
Einfach den Server stoppen auf dem man ist und Anschließend wird man von dem Server gekickt.
Davon ist es unabhängig welchen Command man benutzt um den Server zu stoppen

**Expected behavior:**
Ich hatte gehofft, das ich auf einen anderen Lobby Server verschoben werde, der verfügbar war.

**Environment and used hardware:**
 OS: Debian 10 Buster
 openjdk 8
CloudNet 3.4
Velocity 1.1.9
PaperSpigot 1.8

**Comment by derklaro** [comment]
Can't reproduce. A PR recently fixed a similar issue for 3.5 maybe this is fixed now.
