### ISSUE TITLE
ServiceInfoSnapshot is not being updated and remains the same

### ISSUE THREAD

**Issue by SoneNiko** [CloudNetService/CloudNet-v3#536]
**Description of the bug:**
When using either the CloudNetDriver or CloudNet gradle dependency, if you get a CloudService and get its ServiceInfoSnapshot the information stays the same until it is manually updated.
You can manually update the information by running the command "ser name" to display its information.

**Steps to reproduce this bug:**

To reproduce this bug, create a timer task that prints the cpu usage in the ProcessSnapshot in the ServiceInfoSnapshot to the console. You will notice that it doesnt change unless you manually query it using "service name"

**Expected behavior:**

The Information Should be updated

**Screenshots:**

![image](https://user-images.githubusercontent.com/36677468/128412934-0cd0737c-6031-4cf7-834a-41885a1d4772.png)

**Environment and used hardware:**

 - System specifications: AMD FX 6530
 - OS: Windows 10
 - Version: 3.4

**Comment by derklaro** [comment]
This behaviour is correct. Please take a look in the ServiceProvider it contains a method to force update the service info from the api.

**Comment by SoneNiko** [comment]
That is properly stupid

**Comment by derklaro** [comment]
No that's correct, it's called caching

**Comment by SoneNiko** [comment]
Why would you want to cache information that needs to be accurate?

**Comment by derklaro** [comment]
CloudNet doesn't need these information to be accurate. An update will be published every time something changes on the service (like a player join if you use the bridge module). As I mentioned you can request a forced updated service info by using the service provider (ServiceInfoSnapshot#provider) - that's the thing the service command does. For us there is no need for accurate memory or cpu information as CloudNet itself will not look at these information at all (I mean why? We can't do anything against a high cpu usage...)

**Comment by SoneNiko** [comment]
I get that cloudnet itself doesnt need these infos. But people developing modules need them.I get your point and its good that you can at least force Update it. Thing is if only there was a proper documentation of the API. What you have right now on cloudnetservice.eu is fine for most regular users but not for devs
