### ISSUE TITLE
Large load from the module [CRITICAL]

### ISSUE THREAD

**Issue by glitchring** [CloudNetService/CloudNet-v3#549]
I re-log several times and do timings, and there I see a large load from one CloudNet-Bridge plugin, 140% of the load on the server, please optimize !

![изображение](https://user-images.githubusercontent.com/73692598/132394327-9b40f2e7-678b-4a0e-b74b-4cc5c261338c.png)

**Comment by xxFLORII** [comment]
i don't have this problem.

**Comment by glitchring** [comment]
> 
> 
> i don't have this problem.

this is fifty-fifty, somewhere it is very critical, somewhere everything is fine

**Comment by derklaro** [comment]
We could move the handling of that event into the AsyncPlayerPreLoginEvent indeed. But that might be a breaking change for any plugin developer which relies on the login event call order to allow player connections anyways. A possiblity might be handling some stuff in the async event and some stuff in the sync event. With upcoming service task updates we should think about caching the current task associated with the service anyways.

I will look into this issue again at a later point - the current improvements we are making are breaking the compile lifecycle so there is no real chance fixing this issue within the next few werks :/

**Comment by derklaro** [comment]
Should be gone now... The fix will be included in the upcoming dev/release version. Feel free to re-open when the upcoming version is not fixing your problem :)
