### ISSUE TITLE
Purpur Support

### ISSUE THREAD

**Issue by SageSphinx63920** [CloudNetService/CloudNet-v3#552]
**Description of the new feature:**

Add the Pupur Software to the setup to use is like paper, spigot, etc.

**Reasons for inclusion into the CloudNet code base:**

You can change the default Template but its really difficult 

**Planned audience:**

Everybody can use is. The Software is like paper but implement Dome more Software too.

**Comment by derklaro** [comment]
Interested in opening a pull request?

**Comment by SageSphinx63920** [comment]
I can try to implement it. Yes i can open a pull request

**Comment by SageSphinx63920** [comment]
But I’m not 100% sure if I can do it

**Comment by derklaro** [comment]
The version will be available in the next release 👍

**Comment by SageSphinx63920** [comment]
Thanks
