### ISSUE TITLE
Able to use * in deployment's exclusions

### ISSUE THREAD

**Issue by giqnt** [CloudNetService/CloudNet-v3#556]
**Description of the new feature:**
Able to use * in deployment's exclusions.
ex) 'plugins/*.jar', 'plugins/Network*'
etc.

**Reasons for inclusion into the CloudNet code base:**
this will be very useful for anyone who are using deployment feature

**Planned audience:**
well, it can, but many others might want this too without modules

**Preview of code and documentation:**
like above,
'plugins/*.jar', 'plugins/Network*'

**Additional context:**

**Comment by derklaro** [comment]
Will be available in the upcoming version. All type of [regex](https://en.wikipedia.org/wiki/Regular_expression) should be available for excluding files then.
