### ISSUE TITLE
WaterdogPE

### ISSUE THREAD

**Issue by xxFLORII** [CloudNetService/CloudNet-v3#561]
**Description of the bug:**

**Steps to reproduce this bug:**

1. Start CloudNET the first time
2. select WATERDOG_PE as Proxy software

-->

**Expected behavior:**
WaterdogPE jar file sollte automatisch heruntergeladen werden, was jedoch nicht passiert

**Screenshots:**

**Environment and used hardware:**

**Additional context (optional):**

**Comment by 0utplay** [comment]
There is no support for waterdogpe in 3.4.0-RELEASE. Please follow the issue template and specify the version you are using.

**Comment by derklaro** [comment]
Please use the `feature/waterdog-pe-support` branch if you want to use waterdog with CloudNet 3.4.
