### ISSUE TITLE
Tab complete for paste service <service>

### ISSUE THREAD

**Issue by giqnt** [CloudNetService/CloudNet-v3#584]
**Description of the new feature:** i cannot tab complete services in 'paste service <service>'

**Reasons for inclusion into the CloudNet code base:** because i (and prob many others) use paste a lot and it might helps other too

**Planned audience:** 

**Preview of code and documentation:**

**Additional context:**

**Comment by derklaro** [comment]
This should be included in the next major release iirc @0utplay ?

**Comment by 0utplay** [comment]
Yes that is included in the reworked report module.

**Comment by giqnt** [comment]
@0utplay umm.. so when will 4.0 be released?

**Comment by 0utplay** [comment]
Most things are done, but there is no ETA
