### ISSUE TITLE
Max allowed right margin of 80 characters is way to overkill

### ISSUE THREAD

**Issue by 4zuree** [CloudNetService/CloudNet-v3#6]
The max allowed right margin with an astonishing amount of 80 characters is way to overkill and should be a lot higher. Increasing the max character amount makes the code easier to read and doesn't force developers to shift each and every single parameter of functions or constructors or else into a new line.

I'd recommend to set the max right margin to about 110 up to 130 characters.

**Comment by manuelkollus** [comment]
Why is it overkill if you do it neatly then there's nothing to be said against it?

Even many projects managed by Google adhere to the conventions.
