### ISSUE TITLE
Game States :)

### ISSUE THREAD

**Issue by VerklicktYT** [CloudNetService/CloudNet-v3#618]
**Description of the new feature:**

Ich plane auf meinem Server Bedwars hinzuzufügen, nur das Problem ist, dass ich in der Lobby
Cloud-NPC's stehen haben möchte, welche dich auf einen Bedwars Server schicken. Soweit so gut! 
Das Problem dabei ist halt, dass sich der Spieler evt. auch eine bereits laufende Runde erwischen kann.

Meine Frage deshalb:
Ist es möglich evt. ein Modul für Game-States hinzuzufügen? 

**Reasons for inclusion into the CloudNet code base:**

Weil der Modi von einem Template geladen werden soll und Bungeecord nicht entscheidet, ob ein Spieler
per NPC verschoben wird.

**Planned audience:**

Alle die ein Netzwerk mit Minigames haben und in ihren Modi-Plugins den Game Status setzten wollen!
**Preview of code and documentation:**
idk :/

**Additional context:**

**Comment by juliarn** [comment]
Hey, das CloudNet-Bridge Modul implementiert solche Gamestates bereits. Damit der Server von den Signs/NPCs entfernt wird, muss entweder über die Api auf dem Server der State auf Ingame gesetzt werden `BukkitServerHelper.changeToIngame()` oder die MOTD des Servers muss "ingame" enthalten.

**Comment by VerklicktYT** [comment]
Ohh, danke! 
Habe sowas halt nicht im Wiki gefunden und wusste halt nicht, ob diese Funktion existiert :/

**Comment by VerklicktYT** [comment]
Heißt das ich muss einfach die MOTD vom Paper Server in "ingame" ändern, um den Modi in den Ingame-State zu setzen?

**Comment by juliarn** [comment]
Würde so gehen, ja

**Comment by VerklicktYT** [comment]
Ok, Danke für die Hilfe! :D

**Comment by derklaro** [comment]
Closing as this issue seems resolved. If there are further questions feel free to open a new one!
