### ISSUE TITLE
spigot 1.8.8

### ISSUE THREAD

**Issue by Delta203** [CloudNetService/CloudNet-v3#619]
**Description of the new feature:**

**Reasons for inclusion into the CloudNet code base:**

**Planned audience:**

**Preview of code and documentation:**

**Additional context:**

Hey is it possible to use spigot 1.8.8 as minecraft server. If I use MINECRAFT_SERVER there is just spigot 1.12.2 - 1.18.1. Moreover, if I try to user glowstone-1.8.8 it is not possible for the cloud to download and load the glowstone.jar successfully. Thererfore, I'm asking, can you implement spigot 1.8.8 to CloudNet V3?
Thank you!

**Comment by wasn325** [comment]
The cloud is already capable of using spigot 1.8

The Versions you get shown depend on the java version you used to start the cloud
As the 1.8 version was made with java 6 it might fail to run with newer versions than java 8

**Comment by wasn325** [comment]
Like when you start the cloud with java 17 you get 1.12 (might be wrong) up to 1.18
start the cloud with java 8 and you get 1.8 and so on...

It's also possible to force the installation of 1.8 with --force, but you might have to change the runtime for this task
`tasks task TASK_NAME set javaCommand path/to/java/8/bin/java`

**Comment by Delta203** [comment]
Ah ok thats the thing, I'm currently running java 17. Thanks for your help :)

**Comment by byRoadrunner** [comment]
The issue seems to be solved. If you have any further questions regarding this topic, please open it again.
