### ISSUE TITLE
CloudNPC "Server-wechsel-bug"

### ISSUE THREAD

**Issue by julian-siebert** [CloudNetService/CloudNet-v3#628]
**Description of the bug:**

Ich nutze auf meinem Server ein Plugin, welches per CloudNet API Multiroot-fähig ist.
Sobald das Plugin auf meinem Proxy (Waterfall) ist, dauert es jenachdem, wie oft man auf die NPC's klickt, länger, bis man verbunden ist. (Ich habe mich schon im Support des Developers vom Plugin gemeldet, sie meinten aber es sei ein CloudNet Bug)

**Steps to reproduce this bug:**

Sobald das Plugin auf dem Server ist, scheint alles normal, doch wenn man die CloudNPC's nutzen möchte, um sich auf einen anderen Unterserver zu verbinden, dauert die Verbindung länger als gewohnt.
Je öfter man auf den NPC klickt, desto länger dauert die Verbindung.
Ebenso ist mir aufgefallen, dass sich der Bug, wenn der Proxy schon länger läuft, von selbst löst, ohne etwas in irgendeiner Weise geändert zu haben. Nach jedem Neustart aber war der Bug wieder da.
Das Plugin heißt btw DKBans.

**Expected behavior:**

Normalerweise sollte man sich sofort verbinden können, aber mit dem Plugin dauert es länger.

**Screenshots:**

Hier ein Video, wie der Fehler aussieht: https://www.mediafire.com/file/yq53mrd50iix00x/2022-03-10+12-15-38.mp4/file

Hier ein Screenshot von dem Proxy-Screen, während der Verbindung: 
![image](https://user-images.githubusercontent.com/90093249/157652149-395dceb3-1f8b-40b5-8151-1297026e6595.png)

Anbei auch einen Fehler, der aufgetaucht ist, als ich auf den Server gang: 
![image](https://user-images.githubusercontent.com/90093249/157651943-3920a7f1-2ff2-4e41-8516-b53535335b4d.png)

**Environment and used hardware:**

-Debian 10
-CloudNet 3.4.3
-Zulu JDK 17
-30G Ram (Für die Cloud)
-8 Cpu-Cores

**Additional context (optional):**

Ich habe im Support des Plugin-Developers schon oft nachgefragt, warum dieses Problem nur mit dem Plugin auftaucht.
Sie meinten ich solle hier einen Bug-Report erstellen, um Hilfe zu erhalten.

**Comment by 0utplay** [comment]
Wenn du das Plugin entfernst und es dann nicht mehr auftritt muss das Problem ja bei diesem liegen. (Du bist auch nicht der erste mit diesem Problem)

**Comment by VerklicktTV** [comment]
> Wenn du das Plugin entfernst und es dann nicht mehr auftritt muss das Problem ja bei diesem liegen. (Du bist auch nicht der erste mit diesem Problem)

Sehe ich ehrlich gesagt auch so lmao

**Comment by julian-siebert** [comment]
> Wenn du das Plugin entfernst und es dann nicht mehr auftritt muss das Problem ja bei diesem liegen. (Du bist auch nicht der erste mit diesem Problem)

Kann es trotzdem eventuell möglich sein, dass das Plugin einen Fehler in CloudNet auslöst? Der Developer des Plugins versichert mir, dass keine Fehler beim Plugin liegen.

**Comment by wasn325** [comment]
0utplay meinte das ja

ohne dkbans funktioniert ja alles
und sobald es drauf ist massive delay

Vom Gefühl her blockiert DKBans oder McNative (deren Grundsystem) was

**Comment by julian-siebert** [comment]
> 0utplay meinte das ja
> 
> ohne dkbans funktioniert ja alles und sobald es drauf ist massive delay
> 
> Vom Gefühl her blockiert DKBans oder McNative (deren Grundsystem) was

das weirdeste daran ist, dass sich das Problem manchmal einfach random selber fixed, ohne das irgendwas geändert wurde

**Comment by julian-siebert** [comment]
> > 0utplay meinte das ja
> > ohne dkbans funktioniert ja alles und sobald es drauf ist massive delay
> > Vom Gefühl her blockiert DKBans oder McNative (deren Grundsystem) was
> 
> das weirdeste daran ist, dass sich das Problem manchmal einfach random selber fixed, ohne das irgendwas geändert wurde

Dazu auch nochmal: Das Plugin befindet sich auf dem Proxy! Wenn sich der Bug selbst fixed und ich den Server neustarte, tritt der Fehler wieder auf

**Comment by julian-siebert** [comment]
Ich habe den Dev des Plugins gefragt, wie das Plugin kommuniziert und er meinte, dass anstelle von dem Plugin Messaging Channel, CloudNet genutzt wird

**Comment by 0utplay** [comment]
naja aber ohne das Plugin dauert das ja nicht solange, die Signs oder NPCs nutzen ja auch die CloudNet Sachen zum senden

**Comment by julian-siebert** [comment]
Soll nur extra Info sein, ist ja irgendwie klar. Trotzdem ist der Dev und ich sicher, dass das Plugin anscheinend einen Fehler auslösen muss

**Comment by julian-siebert** [comment]
Ebenso unterstützt das Plugin auch ältere CloudNet Versionen, auf denen der Bug nicht existiert (Laut Dev)

**Comment by 0utplay** [comment]
Der Dev kann sich dann am besten mal in einem Ticket melden

**Comment by julian-siebert** [comment]
> Der Dev kann sich dann am besten mal in einem Ticket melden

Habe dem Dev bescheid gesagt

**Comment by derklaro** [comment]
Ich schließe das mal hier, weil es nicht mit CloudNet alleine reproduzierbar ist.
