### ISSUE TITLE
CloudNPC Update - Permissions um Server zu betreten + Neuen Placeholder

### ISSUE THREAD

**Issue by julian-siebert** [CloudNetService/CloudNet-v3#631]
**Description of the new feature:**

CloudNPC's sollten Services nur per Permission betretbar machen, also wenn Spieler XY kann mit einer Permission nur einen bestimmten Service betreten sollen. Wenn also der Spieler die passende Permission hat, kann er den Service sehen/betreten.

+ NPC's sollten einen neuen Placeholder im Inventar bekommen, um das Template des Services anzeigen zu lassen.

**Reasons for inclusion into the CloudNet code base:**

Es sollte die Möglichkeit geben, Spielern per Permission auf einen anderen Server zu schicken. Das ganze sollte über Permissions laufen, um Spielern perfekte Services zuzuordnen.

**Planned audience:**

Das ganze kann sinnvoll für Minigames sein: Matchmaking!
Nehmen wir an ein Spieler mit dem Rank Bronze hat eine schlechtere Gewinnwahrscheinlichkeit als ein Spieler mit dem Gold Rank, weshalb Gold Spieler auf einen anderen Service gesendet werden sollten.

**Preview of code and documentation:**

Ein Minigame Service, wie z.B. Bedwars, sollte dann per MOTD anzeigen, welche Permission der Spieler braucht, um den Server zu betreten. Erst wenn der Spieler die passende Permission hat, wird der Service im Inventar des NPC's angezeigt und der Service für den Spieler betretbar sein.

**Additional context:**

Wäre alles ein Huge Update und würde die NPC's deutlich verbessern 👍

**Comment by 0utplay** [comment]
Du kannst bereits eine requiredPermission pro Task setzen. Templates sind nicht wirklich möglich / sinnvoll da man mehrere Templates haben kann

**Comment by julian-siebert** [comment]
> Du kannst bereits eine requiredPermission pro Task setzen. Templates sind nicht wirklich möglich / sinnvoll da man mehrere Templates haben kann

Schade, dass das nicht im Wiki steht! Trotzdem Danke für die Information

**Comment by 0utplay** [comment]
Ist es tatsächlich https://cloudnetservice.eu/de/docs/3.4/components/tasks#requiredpermission

**Comment by julian-siebert** [comment]
> Du kannst bereits eine requiredPermission pro Task setzen. Templates sind nicht wirklich möglich / sinnvoll da man mehrere Templates haben kann

Das Problem ist das Bedwars z.B. mehrere Templates (Maps) hat und deshalb alles über templates laufen muss

**Comment by julian-siebert** [comment]
> Ist es tatsächlich https://cloudnetservice.eu/de/docs/3.4/components/tasks#requiredpermission

Ich meine im NPC Wiki

**Comment by julian-siebert** [comment]
> Ist es tatsächlich https://cloudnetservice.eu/de/docs/3.4/components/tasks#requiredpermission

Zudem könnte das ganze deutlich besser beschrieben sein, um Verständnis zu sichern

**Comment by 0utplay** [comment]
> > Du kannst bereits eine requiredPermission pro Task setzen. Templates sind nicht wirklich möglich / sinnvoll da man mehrere Templates haben kann
> 
> Das Problem ist das Bedwars z.B. mehrere Templates (Maps) hat und deshalb alles über templates laufen muss

Du kannst doch die motd nutzen

**Comment by julian-siebert** [comment]
> > > Du kannst bereits eine requiredPermission pro Task setzen. Templates sind nicht wirklich möglich / sinnvoll da man mehrere Templates haben kann
> > 
> > 
> > Das Problem ist das Bedwars z.B. mehrere Templates (Maps) hat und deshalb alles über templates laufen muss
> 
> Du kannst doch die motd nutzen

Mit Permissions???

**Comment by 0utplay** [comment]
> > Ist es tatsächlich https://cloudnetservice.eu/de/docs/3.4/components/tasks#requiredpermission
> 
> Ich meine im NPC Wiki

Das hat mit denen halt nichts zu tun

**Comment by julian-siebert** [comment]
Ich weiß das ich einen Service für alle in Ingame per MOTD setzen kann, das bringt aber jetzt nichts, wenn man ein Matchmaking braucht

**Comment by julian-siebert** [comment]
![image](https://user-images.githubusercontent.com/90093249/158449557-f96e42b5-f230-4282-89f2-ef518be46124.png)
Z.B. Wenn ein Spieler eine Permission hat, die nicht mit der benötigten des Angezeigten Services übereinstimmt, soll der Service unsichtbar in dem NPC für Spieler sein

**Comment by julian-siebert** [comment]
Ich weiß, dass das ziemlich kompliziert ist, aber trotzdem ziemlich sinnvoll, weil einfache Modi mit Dynamischen Services dann ein Matchmaking hätten

**Comment by julian-siebert** [comment]
Leider ist die einzige Möglichkeit, dass gerade hinzukriegen: Eine neue Lobby-Task und Modi-Task zu erstellen und diese per NPC zu verbinden, sodass wenn ein Spieler den Server betritt, in die richtige Lobby sortiert wird, welche die passenden NPC's mit passenden Services hat

**Comment by 0utplay** [comment]
> Ich weiß das ich einen Service für alle in Ingame per MOTD setzen kann, das bringt aber jetzt nichts, wenn man ein Matchmaking braucht

Du kannst da die Motd anzeigen lassen oder auch das extra field

**Comment by 0utplay** [comment]
> ![image](https://user-images.githubusercontent.com/90093249/158449557-f96e42b5-f230-4282-89f2-ef518be46124.png)
> Z.B. Wenn ein Spieler eine Permission hat, die nicht mit der benötigten des Angezeigten Services übereinstimmt, soll der Service unsichtbar in dem NPC für Spieler sein

Naja das ist ziemlich speziell, sowas solltest du eher mit einem eigenen Plugin umsetzen

**Comment by julian-siebert** [comment]
> > ![image](https://user-images.githubusercontent.com/90093249/158449557-f96e42b5-f230-4282-89f2-ef518be46124.png)
> > Z.B. Wenn ein Spieler eine Permission hat, die nicht mit der benötigten des Angezeigten Services übereinstimmt, soll der Service unsichtbar in dem NPC für Spieler sein
> 
> Naja das ist ziemlich speziell, sowas solltest du eher mit einem eigenen Plugin umsetzen

Auch Schade, weil ich wahrscheinlich nicht der einzige bin, der dieses Feature braucht

**Comment by julian-siebert** [comment]
Darf ich überhaupt mir CloudNPC nachmachen, um es dann für meinen Server zu ändern? Frage lieber nach...

**Comment by julian-siebert** [comment]
> Darf ich überhaupt mir CloudNPC nachmachen, um es dann für meinen Server zu ändern? Frage lieber nach...

Unabhängig davon, dass man es einfach auf Github forken kann

**Comment by derklaro** [comment]
https://de.wikipedia.org/wiki/Apache-Lizenz hier stehen alle Lizenzbedingungen. Ich schließe das mal weil das für uns keine Relevanz mehr hat :)
