### ISSUE TITLE
CloudNet should follow Sun's codestyle, not Google's

### ISSUE THREAD

**Issue by 4zuree** [CloudNetService/CloudNet-v3#7]
Sun's codestyle has been practiced by plugin developers and Bukkit itself since millennia. People got used to this particular codestyle and it would be a bad idea to change it, just for one simple reason: Enforcing people to use Google's codestyle, even though they're used to Sun's, might decrease the amount of contributions done to CloudNet.

**Comment by realPanamo** [comment]
Googles codestyle is not that bad, but I agree, just because of the only 2 indents. Not many people do this. I would agree with suns codestyle, but we might just modify the Google codestyle.
