### ISSUE TITLE
Only one subserver can be created

### ISSUE THREAD

**Issue by Darkluke11** [CloudNetService/CloudNet-v3#738]
**Description of the bug:**

Only one Subserver can be created

**Steps to reproduce this bug:**

Install Cloundnet v3 newest version and let create the proxy and the lobby
then get in the task of the lobby and change the minServiceCount to 3
start the cloudnet server new and there is only the Proxy and one Lobby server
if you want to create a new lobby server on the console its not possible

see the screenshots and the Report

![grafik](https://user-images.githubusercontent.com/46169588/180234762-291092af-3d92-4d86-8788-6f41187970ae.png)

![grafik](https://user-images.githubusercontent.com/46169588/180234844-feb8697e-29ff-44ff-ac80-dd81d4d35f06.png)

![grafik](https://user-images.githubusercontent.com/46169588/180234956-42d848f8-8677-4a1b-9591-eba6e278b205.png)

![grafik](https://user-images.githubusercontent.com/46169588/180235139-bfe5c6bb-45e9-43c1-b731-61feb1cf44ab.png)

[logs cloudnet.zip](https://github.com/CloudNetService/CloudNet-v3/files/9160039/logs.cloudnet.zip)

**Comment by 0utplay** [comment]
Please provide the output of **me**

**Comment by Darkluke11** [comment]
![grafik](https://user-images.githubusercontent.com/46169588/180268626-d64cc510-a925-4486-9fba-2b713156b524.png)

**Comment by derklaro** [comment]
The task has a memory of 4096 MB per service configured, but the node already uses ~4300/8096 MB which means that no new service with that amount of memory can be started.

Either increase the memory the node is allowed to use, or decrease the amount of memory each service of the task should use.
