### ISSUE TITLE
IndexOutOfBoundsException in Node class

### ISSUE THREAD

**Issue by barpec12** [CloudNetService/CloudNet-v3#745]
https://github.com/CloudNetService/CloudNet-v3/blob/e381c282a94f0d15693b513e011426bd1c59049a/node/src/main/java/eu/cloudnetservice/node/Node.java#L165
This line causes throwing IndexOutOfBoundsException, when there is no element of index 0.
Removing an element by index works differently than removing an object.
See https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html#remove-int-

**Comment by derklaro** [comment]
Your launcher is outdated. There is no way that the index is missing, as the (new) launcher always passes the argument down.

**Comment by barpec12** [comment]
You are right, updating launcher to a newest version fixes this issue.
Sorry for making an invalid issue.
