### ISSUE TITLE
No default / Backup server

### ISSUE THREAD

**Issue by PhilCode-creator** [CloudNetService/CloudNet-v3#769]
**Description of the bug:**
After installation BungeeCord kick: Could not connect to a default or fallback server

**Steps to reproduce this bug:**

1. Download with wget
2. run installer
3. Installer Values: Eula -> yes, Cluster -> No, Proxy: BungeeCord, Type: -> Minecraft_server, Minecraftserver version paperspigot-1.18.2-latest
4. Connect to server

**Expected behavior:**

Be able to Connect to Server

**Screenshots:**
![xcvxcvxc](https://user-images.githubusercontent.com/55019948/184254388-6fee2ca2-e289-4eed-9960-f3af58d48248.png)

**Environment and used hardware:**

 - System specifications: 64GB ram Intel 7 7600
 - OS: Linux Debian 10
 - Version: 4.3
 

**Additional context (optional):**

I can toggle the screen of Proxy-1 and Lobby-1 both open and no Errors in them
Server IP if you want to try it is: 88.99.145.83

**Comment by derklaro** [comment]
Please attach the proxy log (make sure to remove any ip addresses of clients which might be visible).

**Comment by PhilCode-creator** [comment]
[proxy.txt](https://github.com/CloudNetService/CloudNet-v3/files/9314723/proxy.txt)

**Comment by derklaro** [comment]
Well in that case I need the log of the Lobby server as well 😆

**Comment by PhilCode-creator** [comment]
[latest.log](https://github.com/CloudNetService/CloudNet-v3/files/9314768/latest.log)

**Comment by PhilCode-creator** [comment]
IDK what was it but now it is working thanks anyway
