### ISSUE TITLE
generateRPCBasedApi not working properly?

### ISSUE THREAD

**Issue by RobotHanzo** [CloudNetService/CloudNet-v3#780]
**Description of the bug:**

`java.lang.AbstractMethodError: Receiver class eu.cloudnetservice.wrapper.permission.WrapperPermissionManagement$Impl_NBSG9DAZMY/0x0000000800d49000 does not define or inherit an implementation of the resolved method 'abstract java.util.Collection usersByGroup(java.lang.String)' of interface eu.cloudnetservice.driver.permission.PermissionManagement.`
The above exception was thrown when trying to invoke `CloudNetDriver.instance().permissionManagement().usersByGroup("admin")`

**Steps to reproduce this bug:**

Get a platform plugin (ex. Bukkit plugin) to invoke `CloudNetDriver.instance().permissionManagement().usersByGroup("admin")` and see

-->

**Expected behavior:**

Returns a list of users in that group.

**Potential fix**

After some digging in the code, I found that WrapperPermissionManagement is abstract because it is generated using `generateRPCBasedApi`
Source: https://github.com/CloudNetService/CloudNet-v3/blob/unstable/rewrite/wrapper-jvm/src/main/java/eu/cloudnetservice/wrapper/Wrapper.java#L147
So I guess the way to fix this would be by changing how `generateRPCBasedApi` works?

**Screenshots:**

![image](https://user-images.githubusercontent.com/36107150/184527731-42ad1b80-bc19-4cf5-a98d-6b113efd3e2e.png)

**Environment and used hardware:**

 OS: Ubuntu 20.04
 Version: CloudNet on unstable/rewrite

**Comment by 0utplay** [comment]
Hey, the mentioned commit should fix the issue. Can you please confirm?

**Comment by RobotHanzo** [comment]
#781 does fix the issue, closing it now, thanks!
