### ISSUE TITLE
Auch Nachrichten die nur Admins sehen Editierbar machen.

### ISSUE THREAD

**Issue by KxmischerLasse** [CloudNetService/CloudNet-v3#788]
### Describe the new feature

Nachrichten in jedem Modul komplett Editierbar machen.

### Why do you need this feature?

Ich möchte das wenn ich Nachrichten lese diese Ändern können, da dieses dann besser in das Server Bild passt.

### Alternatives

Es selber im SRC ändern, aber für die welche nicht Coden können währe die Config besser.

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
I don't think that changing these messages is really useful. All messages that get to the user are editable

**Comment by KxmischerLasse** [comment]
Naja, es würde viel besser ins Server Bild passen. Dazu Stört es mich irgendwie wenn ich die Nachricht nicht ändern kann. Ich möchte halt das die Chat Nachrichten zum anderen Teil des Servers passen da es sonst nicht einheitlich ist.
