### ISSUE TITLE
/cl Command Ingame

### ISSUE THREAD

**Issue by KxmischerLasse** [CloudNetService/CloudNet-v3#789]
### Describe the new feature

Der Befehl /cl soll ein Alias für /cloud sein.

### Why do you need this feature?

Damit man nicht immer /cloud ausschreiben muss

### Alternatives

Man könnte /cloud ausschreiben

### Other

In der v3 gab es diesen Alias.

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by derklaro** [comment]
I think typing /cloud vs. /cl is just not that much more work, especially considering that when typing /cl you can tab the cloud command already. Not worth it to accidentally override other plugin commands for a shortcut imo.
