### ISSUE TITLE
Waterdog for better support for Nukkit.

### ISSUE THREAD

**Issue by SchdowNVIDIA** [CloudNetService/CloudNet-v3#81]
**Please describe the proposed feature**<br>

Add Waterdog. It's a Waterfall fork working for Nukkit and all types of bedrock server software. Very fast and good. It supports 100% bungeecord plugins.

**Additional context**

**Comment by realPanamo** [comment]
Hey, 
If WaterDog supports bungee plugins, you should be able to use it with cloudnet, if it also has a bungeecord config.yml. You could try to place the server software named "bungee.jar" in the template.

**Comment by SchdowNVIDIA** [comment]
It's doesn't work right, because of the new settings. i hope you can update cloudnet for waterdog would be very nice to have a full nukkit network with bungee/waterdog.

**Comment by realPanamo** [comment]
I just checked, you need to add a new listener for waterdog to the config.yml, so CloudNet sets the host address. So it should work, or did you experience other issues?
