### ISSUE TITLE
Banner Module

### ISSUE THREAD

**Issue by strich3** [CloudNetService/CloudNet-v3#843]
### Describe the new feature

It's like the Sign Module but with Banners. Would love to see this in the Version 4!

### Why do you need this feature?

I mean it's not needed. It's just an Idea

### Alternatives

Sign Module

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
hardly think that this effort is worth it. Moreover, I wonder how you could display something on the banners there.

**Comment by strich3** [comment]
> hardly think that this effort is worth it. Moreover, I wonder how you could display something on the banners there.

you could use holograms

**Comment by 0utplay** [comment]
Would each banner open an inventory like npcs or is it really like a sign?

**Comment by strich3** [comment]
> Would each banner open an inventory like npcs or is it really like a sign?

It works like signs, if you click on a banner it will send you to the game server. And Above the banner are the informations

**Comment by derklaro** [comment]
Not yet convinced that we need that feature 100%, but I will leave the issue open for later consideration.

**Comment by HttpPython** [comment]
i love your idea man

**Comment by strich3** [comment]
yeah, i guess it would be cool! :)

**Comment by strich3** [comment]
Any Updates on this?

**Comment by 0utplay** [comment]
I dont think there are enough people interested in this.
