### ISSUE TITLE
Create a menu where you can put lobbies and make a random connection system with a group

### ISSUE THREAD

**Issue by Prismaexe** [CloudNetService/CloudNet-v3#860]
### Describe the new feature

It would be cool to be able to create our own menu as with the npc with the content of the servers which are online as a lobby system if several are created when there are too many members then all the lobby would be grouped in a single item

And it would be cool to be able to create different server groups in order to make rancomized connections like for servers, bedwars, skywars and other games

### Why do you need this feature?

Because it would be easier for all users to see this directly implemented at cloud net instead of coding our plugins ourselves

### Alternatives

Yes of course, we can develop our own plugins but it would be really cooler if it was directly implemented

### Issue uniqueness

- [x] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
Sorry, but I don't see a lot of people using that. It sounds very specific and special to your server. Also I think that implementing such an menu is not very hard and everyone running a server should be able to do exactly that.

If you need any help using the api feel free to ask on our discord.
