### ISSUE TITLE
CloudNpc

### ISSUE THREAD

**Issue by OneProz** [CloudNetService/CloudNet-v3#889]
### Stacktrace

```
Paste your paste link or the raw stack trace here. DO NOT REMOVE THE BACKTICKS!
```

### Actions to reproduce

I started cloudnet, created a npc and stopped the server. After it started again i hopped on the server and the npc isnt there anymore. Btw when activating immitateplayer you will get kicked from the server.
![Unbenannt](https://user-images.githubusercontent.com/114934005/193603587-0cc961e2-6793-4dc4-b262-71b8d0c059b2.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/114934005/193603593-d9a965f2-e91d-43f7-82b8-c45c58970340.PNG)

### CloudNet version

rc2

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
Please follow the issue template.
Provide the Stacktrace in the specific block and run the me command.
