### ISSUE TITLE
Bring back connectHostAddress

### ISSUE THREAD

**Issue by whereareiam** [CloudNetService/CloudNet-v3#896]
### Describe the new feature

Previously there was a connectHostAddress in V3 and I suggest bringing it back. It brought great relief to people who have a server at home and do not have a static IP. Through this function, the proxy connected the players to the servers using an external IP, and the servers themselves were launched on the internal IP. Would great to see this feature again in this or a similar form.

### Why do you need this feature?

It will be helpful for me and people with a similar situation. This will be applicable, for example, to testing or creating servers on a home machine.

### Alternatives

I haven't found any alternatives to this feature right now, so I don't currently have the option to upgrade from V3 to V4 in the future.

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
Why don't you just use a vlan for that. Adding the connect host address only leads to a very high complexity for developers and end users

**Comment by whereareiam** [comment]
> Why don't you just use a vlan for that. Adding the connect host address only leads to a very high complexity for developers and end users

I have no idea what vlan is, I tried to read it in Google, but it didn’t help much either.

**Comment by 0utplay** [comment]
I would recommend that you contact your network admin. He can set this up for you.

**Comment by 0utplay** [comment]
Closed, as it is seems not really needed - creates more problems than it solves
