### ISSUE TITLE
Velocity not downloading

### ISSUE THREAD

**Issue by mpztilera** [CloudNetService/CloudNet-v3#90]
**Describe the bug**<br>

**Steps for reproducing**<br>

**Expected behavior**<br>

**Screenshots**<br>

**Please provide us information about your environment and used assets**

**Additional context**<br>

**Comment by byRoadrunner** [comment]
Could you please fill the template with the additional informations and the description of the bug you are experiencing.

**Comment by realPanamo** [comment]
The Velocity CI seems to be down, I just removed the option to download velocity from the cloud in #96 .
