### ISSUE TITLE
CloudFlare R2 Support

### ISSUE THREAD

**Issue by Eptiiix** [CloudNetService/CloudNet-v3#912]
### Describe the new feature

Cloudflare just released their R2 Storage and its way better and faster then aws.
I think it would be an good idea to make the S3 module an provider independent module as the cloudflare r2 supports the s3 api.

### Why do you need this feature?

to store templates

### Alternatives

only worse than r2

### Other

i tried to use the current s3 module but it looks like the amazonaws url is hard-coded

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
You can change the endpoint in the s3 module config

**Comment by derklaro** [comment]
The configuration option for that is called `endpointOverride`. Just set it to the r2 cloudflarestorage endpoint and it should work
