### ISSUE TITLE
Gruppenname wird nicht angezeigt

### ISSUE THREAD

**Issue by KxmischerLasse** [CloudNetService/CloudNet-v3#917]
### Stacktrace

```
Paste your paste link or the raw stack trace here. DO NOT REMOVE THE BACKTICKS!
```

### Actions to reproduce

1. Gruppe von einem Task entfernen

### CloudNet version

4.0.0-RC3

### Other

![Unbenannt](https://user-images.githubusercontent.com/67797390/195977324-c2fa43d6-5df5-4a83-b94d-b4b28c77f873.PNG)

Hier sieht man das die Gruppe nicht angezeigt wird.

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by derklaro** [comment]
We got it, please don't open a new issue for each message
