### ISSUE TITLE
Auslastung der Nodes bei /cloud clu nodes & clu nodes

### ISSUE THREAD

**Issue by KxmischerLasse** [CloudNetService/CloudNet-v3#919]
### Describe the new feature

Das man über /cloud clu nodes die Auslastung der einzelnen Nodes sehen kann. Ansonsten muss man immer auf den jeweiligen Node Connecten was auf dauer nervt.

### Why do you need this feature?

Es währe hilfreich schnell zu sehen wie grade die Nodes ausgelastet sind

### Alternatives

Auf den Node sich über z.b. Putty Connecten und die Auslastung über "me" nachschauen

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
You can use `clu node <node>` to display these information about a specific node. Adding these information to the overview is too much from my point of view.
