### ISSUE TITLE
CloudNet-Chat ignores group color

### ISSUE THREAD

**Issue by Remynfv** [CloudNetService/CloudNet-v3#926]
### Actions to reproduce

Version: CloudNet Blizzard 4.0.0-RC4 ab12241
Using both CloudNet-Chat and CloudNet-SimpleNameTags:
```
/cloud perms group admin set prefix "&x&f&f&0&0&f&fAdmin &4| "
/cloud perms group admin set color &7
```
Join the admin group.

Player list looks like this:
![image](https://user-images.githubusercontent.com/15258372/196071848-30b2e333-2ec2-4b68-b4ea-582d5a7b4ae4.png)

While chat looks like this, ignoring the color:
![image](https://user-images.githubusercontent.com/15258372/196071786-ea370fb7-d108-4098-967f-265825ebbb48.png)

### CloudNet version

CloudNet Blizzard 4.0.0-RC4 ab12241

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by wasn325** [comment]
It's not a bug. The Chat Plugin is configurable. Look into the config (/plugins/Cloudnet-Chat) and you find the format used to show your message.

**Comment by Remynfv** [comment]
> It's not a bug. The Chat Plugin is configurable. Look into the config (/plugins/Cloudnet-Chat) and you find the format used to show your message.

Oh, wild. Maybe the default should be changed to match then? Just a thing to consider for consistency at that point.

**Comment by derklaro** [comment]
The color property is a special setting which was added for the tablist only. We're not doing anything with it - it's minecraft which applied the color code to the entry. As the setting was introduced in 1.13 we need to change the config either accordingly to the format of 1.13+ or 1.8 - 1.12 (altough I would prefer 1.13). @0utplay wdyt?

**Comment by 0utplay** [comment]
I agree on changing the default configuration to 1.13+
