### ISSUE TITLE
CloudNPC (Not updating)

### ISSUE THREAD

**Issue by strich3** [CloudNetService/CloudNet-v3#937]
### Actions to reproduce

If i wanna update the NPC MOTD or the MaxPlayers, it won't work. But if i respawn (edit) the NPC then it shows the right MOTD and player count. So basically the NPC won't update until i edit it.
![image](https://user-images.githubusercontent.com/56207893/197408040-b6879e71-3b0c-4c9a-a19b-f6b212b79177.png)

### CloudNet version

 CloudNet Blizzard 4.0.0-RC4-ab12241b

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
Hey, we've developed a fix for the problem you discribed in this issue.
I would ask you to try it using this branch `fix/npc-ingame-items`. You just have to set the updateBranch in the launcher.cnl to the given branch.
As always make sure to backup your files before testing with the fixed branch.

**Comment by strich3** [comment]
Thanks, it seems to work now!

**Comment by strich3** [comment]
Also, if we are already on that topic. Is there a way to display full services or ingame services in the inventory?
