### ISSUE TITLE
ServiceInfoSnapshot

### ISSUE THREAD

**Issue by HttpPython** [CloudNetService/CloudNet-v3#950]
### Describe the new feature

well i would like and many others would like it too if you guys could add methodes like isRunning() getState() and so like we can get the motd, onlinePlayers, maxPlayers and more.

### Why do you need this feature?

Its easier for people who would like to code a server menu or lobbyswitcher

### Alternatives

no

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
The bridge already features these options. Use the BridgeServiceProperties to extract these information from a ServiceInfoSnapshot.
