### ISSUE TITLE
Downtime Discord Alert

### ISSUE THREAD

**Issue by LeNinjaHD** [CloudNetService/CloudNet-v3#971]
### Describe the new feature

Add a module which sends a Message do A Discord Webhook, if a service wont start, or a Node goes offline.

### Why do you need this feature?

This helps with finding issues with your cluster more quickly

### Alternatives

Maybe an external Program, that pings cloudnet to see if it is online?

### Issue uniqueness

- [x] Yes, this issue is unique. There are no similar issues.

**Comment by derklaro** [comment]
This is nothing we will integrate directly into CloudNet, you (or any other developer) can write a module which does exactly what you described.
