### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by strich3** [CloudNetService/CloudNet-v3#982]
### Actions to reproduce

Wenn man austimed auf einem Server ist man noch immer in der Cloud als online registriert und kann somit nicht joinen bis die Cloud Neugestartet wurde!

### CloudNet version

CloudNet Blizzard 4.0.0-RC6-SNAPSHOT 45e96472

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by derklaro** [comment]
You need to provide more info so that we can reporoduce the issue (like proxy & server version)

**Comment by strich3** [comment]
Server Version is Prismarine Current: git-Prismarine-"20d9554" (MC: 1.19.2), and the Proxy Version is waterfall

**Comment by 0utplay** [comment]
Might be outdated
