### ISSUE TITLE
Bridge packet error

### ISSUE THREAD

**Issue by HttpPython** [CloudNetService/CloudNet-v3#983]
### Stacktrace

```
Paste your paste link or the raw stack trace here. DO NOT REMOVE THE BACKTICKS!
```
https://hastebin.com/fuqimorina.sql

### Actions to reproduce

i just joined my network

### CloudNet version

RC5

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by derklaro** [comment]
Might be related to missing overrides for the methods which are returning a player provider
