### ISSUE TITLE
Adding AutoPlug as default server-software

### ISSUE THREAD

**Issue by Osiris-Team** [CloudNetService/CloudNet-v3#989]
### Describe the new feature

AutoPlug can act as a server wrapper and provide functionality like automated mods/plugins/server/java updating. More info here: https://www.spigotmc.org/resources/autoplug-automatic-updater-for-plugins-mods-server-java-itself.78414/

It should be pretty easy to implement to since there is a static link to the latest jar.

### Why do you need this feature?

Full disclosure: I am the developer of it, and I think this would increase its popularity.

### Alternatives

-

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
I don't see the use case for that as it would not work with templates and version installers.

**Comment by Osiris-Team** [comment]
@0utplay I don't know what those things are, but you can think of autoplug as a regular server jar, like the paper jar for example.

**Comment by 0utplay** [comment]
That does not change anything as it won't work and it does not have any benefit over using paper in combination with cloudnet.
