### ISSUE TITLE
service starts multiple times but as prepared on same port

### ISSUE THREAD

**Issue by Eptiiix** [CloudNetService/CloudNet-v3#994]
### Stacktrace

```
Paste your paste link or the raw stack trace here. DO NOT REMOVE THE BACKTICKS!
```

### Actions to reproduce

got 5 nodes in a cluster with the following modules:
- Bridge
- CloudFlare
- MySQL
- Signs
- S3 Storage
- SyncProxy
- Smart

The task with this error has smart enabled with the following config:
```
    "smartConfig": {
      "enabled": true,
      "priority": 10,
      "maxServices": 5,
      "preparedServices": 0,
      "smartMinServiceCount": 1,
      "splitLogicallyOverNodes": true,
      "directTemplatesAndInclusionsSetup": true,
      "templateInstaller": "INSTALL_ALL",
      "autoStopTimeByUnusedServiceInSeconds": 180,
      "percentOfPlayersToCheckShouldStopTheService": 0,
      "forAnewInstanceDelayTimeInSeconds": 300,
      "percentOfPlayersForANewServiceByInstance": 100
    }
```

### CloudNet version

CloudNet Blizzard 4.0.0-RC6-SNAPSHOT 45e96472

### Other

Tasks getting started multiple times but as prepared on same port and screen also reacts on the prepared ones.
I am only aware of the error since i use more than 2 nodes.

Image of the service list part:
https://ibb.co/Z6dxt4B

Image of the screen command:
https://ibb.co/kcXmbRv

Image of stopping service:
https://ibb.co/GnV461X

### Edit:
if i change the maxServices of the task to 3 i get 1 running service and 1 prepared service.
My global minServiceCount in this task is 1.
If i disable smartConfig i have no problems.

### Issue uniqueness

- [X] Yes, this issue is unique. There are no similar issues.

**Comment by 0utplay** [comment]
Hi! Thank you for your error message, we think we have found a solution to the problem. It would be good if you could test if this solves the problem for you.

To test our fix you would have to set the updateBranch in launcher.cnl to `better-create-timeout-handling` and then restart once. But I ask you, as always with such tests, to make a backup and not to test it with the production system.
